-- Seed: pre-provision Lightspeed Systems people into the users directory.
-- Idempotent on email; `sub` is a stable seed marker (replaced with the real
-- IdP subject when the person first authenticates). No password set — these are
-- directory entries (also populate the Organization surface). role defaults to 'user'.
INSERT INTO "users" ("sub", "email", "name") VALUES
  ('seed:wlawrence@lightspeedsystems.com', 'wlawrence@lightspeedsystems.com', 'Wes Lawrence'),
  ('seed:hjames@lightspeedsystems.com', 'hjames@lightspeedsystems.com', 'Heather James'),
  ('seed:mcanales@lightspeedsystems.com', 'mcanales@lightspeedsystems.com', 'Morgan Canales'),
  ('seed:abennett@lightspeedsystems.com', 'abennett@lightspeedsystems.com', 'Amy Bennett'),
  ('seed:kwilliamson@lightspeedsystems.com', 'kwilliamson@lightspeedsystems.com', 'Kathy Williamson'),
  ('seed:patrick@lightspeedsystems.com', 'patrick@lightspeedsystems.com', 'Patrick Chapa'),
  ('seed:jadkins@lightspeedsystems.com', 'jadkins@lightspeedsystems.com', 'Jonathan Adkins'),
  ('seed:ntribo@lightspeedsystems.com', 'ntribo@lightspeedsystems.com', 'Nicole Tribo'),
  ('seed:ahesse@lightspeedsystems.com', 'ahesse@lightspeedsystems.com', 'Alex Hesse'),
  ('seed:rpassanisi@lightspeedsystems.com', 'rpassanisi@lightspeedsystems.com', 'Ryan Passanisi'),
  ('seed:mdurando@lightspeedsystems.com', 'mdurando@lightspeedsystems.com', 'Mike Durando'),
  ('seed:michael@lightspeedsystems.com', 'michael@lightspeedsystems.com', 'Michael Boggess'),
  ('seed:john@lightspeedsystems.com', 'john@lightspeedsystems.com', 'John Genter'),
  ('seed:jmorris@lightspeedsystems.com', 'jmorris@lightspeedsystems.com', 'Juliana Morris'),
  ('seed:fromero@lightspeedsystems.com', 'fromero@lightspeedsystems.com', 'Frank Romero'),
  ('seed:wing@lightspeedsystems.com', 'wing@lightspeedsystems.com', 'Wing Mar'),
  ('seed:tngo@lightspeedsystems.com', 'tngo@lightspeedsystems.com', 'Tu Ngo'),
  ('seed:sgillani@lightspeedsystems.com', 'sgillani@lightspeedsystems.com', 'Syed Gillani'),
  ('seed:mwittry@lightspeedsystems.com', 'mwittry@lightspeedsystems.com', 'Marie Wittry'),
  ('seed:jrodriguez@lightspeedsystems.com', 'jrodriguez@lightspeedsystems.com', 'Juan Rodriguez'),
  ('seed:jkhazma@lightspeedsystems.com', 'jkhazma@lightspeedsystems.com', 'Jiana Khazma'),
  ('seed:gfunk@lightspeedsystems.com', 'gfunk@lightspeedsystems.com', 'Gregory Funk'),
  ('seed:cmeyer@lightspeedsystems.com', 'cmeyer@lightspeedsystems.com', 'Cameron Meyer'),
  ('seed:aybarra@lightspeedsystems.com', 'aybarra@lightspeedsystems.com', 'Abraham Ybarra'),
  ('seed:dmunoz@lightspeedsystems.com', 'dmunoz@lightspeedsystems.com', 'Dante Munoz'),
  ('seed:sdunham@lightspeedsystems.com', 'sdunham@lightspeedsystems.com', 'Scott Dunham'),
  ('seed:ryan@lightspeedsystems.com', 'ryan@lightspeedsystems.com', 'Ryan Bond'),
  ('seed:mstewart@lightspeedsystems.com', 'mstewart@lightspeedsystems.com', 'Maddie Stewart'),
  ('seed:kolson@lightspeedsystems.com', 'kolson@lightspeedsystems.com', 'Kyle Olson'),
  ('seed:jlaprocido@lightspeedsystems.com', 'jlaprocido@lightspeedsystems.com', 'James Laprocido'),
  ('seed:jbowman@lightspeedsystems.com', 'jbowman@lightspeedsystems.com', 'Jake Bowman'),
  ('seed:asynos@lightspeedsystems.com', 'asynos@lightspeedsystems.com', 'Adrienne Synos'),
  ('seed:kmcdermott@lightspeedsystems.com', 'kmcdermott@lightspeedsystems.com', 'Kate McDermott'),
  ('seed:ddunn@lightspeedsystems.com', 'ddunn@lightspeedsystems.com', 'Daniel Dunn'),
  ('seed:jwoolverton@lightspeedsystems.com', 'jwoolverton@lightspeedsystems.com', 'Justin Woolverton'),
  ('seed:cdunn@lightspeedsystems.com', 'cdunn@lightspeedsystems.com', 'Chris Dunn'),
  ('seed:brad@lightspeedsystems.com', 'brad@lightspeedsystems.com', 'Brad White'),
  ('seed:ssmith@lightspeedsystems.com', 'ssmith@lightspeedsystems.com', 'Spencer Smith'),
  ('seed:afowler@lightspeedsystems.com', 'afowler@lightspeedsystems.com', 'Andrew Fowler'),
  ('seed:jdelagarrigue@lightspeedsystems.com', 'jdelagarrigue@lightspeedsystems.com', 'Jake de la Garrigue'),
  ('seed:bbrown@lightspeedsystems.com', 'bbrown@lightspeedsystems.com', 'Brooke Brown'),
  ('seed:bgould@lightspeedsystems.com', 'bgould@lightspeedsystems.com', 'Becky Gould'),
  ('seed:vernie@lightspeedsystems.com', 'vernie@lightspeedsystems.com', 'Vernie Ogden'),
  ('seed:svillegas@lightspeedsystems.com', 'svillegas@lightspeedsystems.com', 'Sergio Villegas'),
  ('seed:mmcgovern@lightspeedsystems.com', 'mmcgovern@lightspeedsystems.com', 'Michelle McGovern'),
  ('seed:sdrouin@lightspeedsystems.com', 'sdrouin@lightspeedsystems.com', 'Sabrina Drouin'),
  ('seed:ngreig@lightspeedsystems.com', 'ngreig@lightspeedsystems.com', 'Niki Greig'),
  ('seed:mduhon@lightspeedsystems.com', 'mduhon@lightspeedsystems.com', 'Megan Duhon'),
  ('seed:lmcnair@lightspeedsystems.com', 'lmcnair@lightspeedsystems.com', 'Lauren McNair'),
  ('seed:acribari@lightspeedsystems.com', 'acribari@lightspeedsystems.com', 'Andrew Cribari'),
  ('seed:aszabo@lightspeedsystems.com', 'aszabo@lightspeedsystems.com', 'Alexander Szabo'),
  ('seed:jduer@lightspeedsystems.com', 'jduer@lightspeedsystems.com', 'Jennifer Duer'),
  ('seed:whellems-moody@lightspeedsystems.com', 'whellems-moody@lightspeedsystems.com', 'William Hellems-Moody'),
  ('seed:brocka@lightspeedsystems.com', 'brocka@lightspeedsystems.com', 'Brock Anderson')
ON CONFLICT ("email") DO NOTHING;
