-- 0023 Load the OFFICIAL Lightspeed org chart (224 people) as the single
-- source of truth for the Org tree. Source: 'Lightspeed Systems — Org Chart'
-- provided by Brooke 2026-07-07. People are keyed by a canonical
-- first.last@lightspeedsystems.com email derived from their full name; titles
-- are stored free-text (the Org tree uses users.title when no job_titles link).
-- The prior demo directory (short-handle @lightspeedsystems.com seeds from 0004/
-- 0017/0020) is deactivated so only the official chart shows; real accounts
-- (@st6partners.com etc.) are untouched. leader_badge=ELT for the CEO + direct
-- reports. Idempotent: ON CONFLICT(email) upsert + set-based manager wiring.
DO $$
BEGIN
  -- 1) Retire the old demo directory (only @lightspeedsystems.com seeds).
  UPDATE users SET is_active = false, updated_at = now()
  WHERE email LIKE '%@lightspeedsystems.com';
END $$;
--> statement-breakpoint

-- 2) Upsert every person (manager set in step 3).
INSERT INTO users (sub, email, name, title, leader_badge, is_active) VALUES
  ('seed:brian.thomas@lightspeedsystems.com', 'brian.thomas@lightspeedsystems.com', 'Brian Thomas', 'CEO & Founder', 'ELT', true),
  ('seed:abraham.ybarra@lightspeedsystems.com', 'abraham.ybarra@lightspeedsystems.com', 'Abraham Ybarra', 'Lead Technical Support Specialist', NULL, true),
  ('seed:adrian.rios.alvarez@lightspeedsystems.com', 'adrian.rios.alvarez@lightspeedsystems.com', 'Adrian Rios Alvarez', 'Salesforce Product Manager', NULL, true),
  ('seed:adrienne.synos@lightspeedsystems.com', 'adrienne.synos@lightspeedsystems.com', 'Adrienne Synos', 'Senior Accounting Manager', NULL, true),
  ('seed:aiyana.mathew@lightspeedsystems.com', 'aiyana.mathew@lightspeedsystems.com', 'Aiyana Mathew', 'Lead Senior Software Engineer', NULL, true),
  ('seed:albert.garcia@lightspeedsystems.com', 'albert.garcia@lightspeedsystems.com', 'Albert Garcia', 'Student Safety Specialist', NULL, true),
  ('seed:alecia.boggess@lightspeedsystems.com', 'alecia.boggess@lightspeedsystems.com', 'Alecia Boggess', 'Strategic Account Manager', NULL, true),
  ('seed:alex.wade@lightspeedsystems.com', 'alex.wade@lightspeedsystems.com', 'Alex Wade', 'Staff Frontend Engineer', NULL, true),
  ('seed:alexander.crouse@lightspeedsystems.com', 'alexander.crouse@lightspeedsystems.com', 'Alexander Crouse', 'Strategic Solutions Engineer', NULL, true),
  ('seed:alexander.doria@lightspeedsystems.com', 'alexander.doria@lightspeedsystems.com', 'Alexander Doria', 'Machine Learning Engineer', NULL, true),
  ('seed:alexander.hesse@lightspeedsystems.com', 'alexander.hesse@lightspeedsystems.com', 'Alexander Hesse', 'Senior Systems Administrator', NULL, true),
  ('seed:alexander.sands@lightspeedsystems.com', 'alexander.sands@lightspeedsystems.com', 'Alexander Sands', 'Strategic Solutions Engineer', NULL, true),
  ('seed:alexander.szabo@lightspeedsystems.com', 'alexander.szabo@lightspeedsystems.com', 'Alexander Szabo', 'Business Analyst', NULL, true),
  ('seed:alexander.woods@lightspeedsystems.com', 'alexander.woods@lightspeedsystems.com', 'Alexander Woods', 'Associate Technical Product Manager', NULL, true),
  ('seed:alyssa.ann.silva@lightspeedsystems.com', 'alyssa.ann.silva@lightspeedsystems.com', 'Alyssa Ann Silva', 'Customer Operations Analyst', NULL, true),
  ('seed:alyssa.russo@lightspeedsystems.com', 'alyssa.russo@lightspeedsystems.com', 'Alyssa Russo', 'Senior Customer Operations Manager', NULL, true),
  ('seed:amanda.gorena@lightspeedsystems.com', 'amanda.gorena@lightspeedsystems.com', 'Amanda Gorena', 'Director Corporate Marketing', NULL, true),
  ('seed:amy.bennett@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com', 'Amy Bennett', 'Chief of Staff', 'ELT', true),
  ('seed:andrew.cribari@lightspeedsystems.com', 'andrew.cribari@lightspeedsystems.com', 'Andrew Cribari', 'Senior QA Engineer', NULL, true),
  ('seed:andrew.fowler@lightspeedsystems.com', 'andrew.fowler@lightspeedsystems.com', 'Andrew Fowler', 'Account Executive', NULL, true),
  ('seed:andrew.hecht@lightspeedsystems.com', 'andrew.hecht@lightspeedsystems.com', 'Andrew Hecht', 'Solutions Architect', NULL, true),
  ('seed:andy.bennetta@lightspeedsystems.com', 'andy.bennetta@lightspeedsystems.com', 'Andy Bennetta', 'Team Lead Technical Support', NULL, true),
  ('seed:angela.mazza@lightspeedsystems.com', 'angela.mazza@lightspeedsystems.com', 'Angela Mazza', 'Senior Student Safety Specialist', NULL, true),
  ('seed:anita.krueger@lightspeedsystems.com', 'anita.krueger@lightspeedsystems.com', 'Anita Krueger', 'Site Reliability Engineer', NULL, true),
  ('seed:ann.marie.martinez@lightspeedsystems.com', 'ann.marie.martinez@lightspeedsystems.com', 'Ann Marie Martinez', 'Strategic Account Manager', NULL, true),
  ('seed:armahn.turk@lightspeedsystems.com', 'armahn.turk@lightspeedsystems.com', 'Armahn Turk', 'Student Safety Specialist', NULL, true),
  ('seed:austin.sweet@lightspeedsystems.com', 'austin.sweet@lightspeedsystems.com', 'Austin Sweet', 'Strategic Solutions Engineer', NULL, true),
  ('seed:ava.friloux@lightspeedsystems.com', 'ava.friloux@lightspeedsystems.com', 'Ava Friloux', 'Intern', NULL, true),
  ('seed:benjamin.thomas@lightspeedsystems.com', 'benjamin.thomas@lightspeedsystems.com', 'Benjamin Thomas', 'Intern', NULL, true),
  ('seed:bradley.rowe@lightspeedsystems.com', 'bradley.rowe@lightspeedsystems.com', 'Bradley Rowe', 'Manager, Strategic Solutions Engineering', NULL, true),
  ('seed:bradley.white@lightspeedsystems.com', 'bradley.white@lightspeedsystems.com', 'Bradley White', 'Principal Application Security Engineer', NULL, true),
  ('seed:braedon.mulder@lightspeedsystems.com', 'braedon.mulder@lightspeedsystems.com', 'Braedon Mulder', 'Intern', NULL, true),
  ('seed:brandon.jones@lightspeedsystems.com', 'brandon.jones@lightspeedsystems.com', 'Brandon Jones', 'QA Engineer', NULL, true),
  ('seed:brian.truong@lightspeedsystems.com', 'brian.truong@lightspeedsystems.com', 'Brian Truong', 'Data Platform Manager', NULL, true),
  ('seed:brock.anderson@lightspeedsystems.com', 'brock.anderson@lightspeedsystems.com', 'Brock Anderson', 'Senior Director Strategic Programs', NULL, true),
  ('seed:brock.meadors@lightspeedsystems.com', 'brock.meadors@lightspeedsystems.com', 'Brock Meadors', 'Senior Engineering Manager', NULL, true),
  ('seed:brooke.brown@lightspeedsystems.com', 'brooke.brown@lightspeedsystems.com', 'Brooke Brown', 'Renewals Specialist', NULL, true),
  ('seed:brooke.friedman@lightspeedsystems.com', 'brooke.friedman@lightspeedsystems.com', 'Brooke Friedman', 'Intern', NULL, true),
  ('seed:bryan.anderson@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com', 'Bryan Anderson', 'Senior Engineering Manager', NULL, true),
  ('seed:bryan.steele@lightspeedsystems.com', 'bryan.steele@lightspeedsystems.com', 'Bryan Steele', 'Intern', NULL, true),
  ('seed:caitlin.mcdermott@lightspeedsystems.com', 'caitlin.mcdermott@lightspeedsystems.com', 'Caitlin Mcdermott', 'Director of Product Management Analytics', NULL, true),
  ('seed:cameron.meyer@lightspeedsystems.com', 'cameron.meyer@lightspeedsystems.com', 'Cameron Meyer', 'Technical Escalation Engineer', NULL, true),
  ('seed:carl.ahlstrand@lightspeedsystems.com', 'carl.ahlstrand@lightspeedsystems.com', 'Carl Ahlstrand', 'Lead Software Engineer', NULL, true),
  ('seed:casey.butera@lightspeedsystems.com', 'casey.butera@lightspeedsystems.com', 'Casey Butera', 'Strategic Account Manager', NULL, true),
  ('seed:casey.hann@lightspeedsystems.com', 'casey.hann@lightspeedsystems.com', 'Casey Hann', 'Senior Manager Customer Experience', NULL, true),
  ('seed:charles.bryant@lightspeedsystems.com', 'charles.bryant@lightspeedsystems.com', 'Charles Bryant', 'Manager, Strategic Solutions Engineering', NULL, true),
  ('seed:charushila.awhad@lightspeedsystems.com', 'charushila.awhad@lightspeedsystems.com', 'Charushila Awhad', 'QA Automation Engineer', NULL, true),
  ('seed:chase.masiel@lightspeedsystems.com', 'chase.masiel@lightspeedsystems.com', 'Chase Masiel', 'Content Categorization Specialist', NULL, true),
  ('seed:chasity.lyson@lightspeedsystems.com', 'chasity.lyson@lightspeedsystems.com', 'Chasity Lyson', 'Technical Escalation Engineer', NULL, true),
  ('seed:christian.trahan@lightspeedsystems.com', 'christian.trahan@lightspeedsystems.com', 'Christian Trahan', 'Software Engineer', NULL, true),
  ('seed:christina.atkinson@lightspeedsystems.com', 'christina.atkinson@lightspeedsystems.com', 'Christina Atkinson', 'Solutions Engineer', NULL, true),
  ('seed:christina.mares@lightspeedsystems.com', 'christina.mares@lightspeedsystems.com', 'Christina Mares', 'Student Safety Specialist', NULL, true),
  ('seed:christopher.dunn@lightspeedsystems.com', 'christopher.dunn@lightspeedsystems.com', 'Christopher Dunn', 'Associate Account Executive', NULL, true),
  ('seed:christopher.newkirk@lightspeedsystems.com', 'christopher.newkirk@lightspeedsystems.com', 'Christopher Newkirk', 'Lead Site Reliability Engineer', NULL, true),
  ('seed:christopher.spink@lightspeedsystems.com', 'christopher.spink@lightspeedsystems.com', 'Christopher Spink', 'Strategic Account Executive', NULL, true),
  ('seed:christopher.travis@lightspeedsystems.com', 'christopher.travis@lightspeedsystems.com', 'Christopher Travis', 'Chief Revenue Officer', 'ELT', true),
  ('seed:cindy.moore@lightspeedsystems.com', 'cindy.moore@lightspeedsystems.com', 'Cindy Moore', 'Training & Enablement Manager', NULL, true),
  ('seed:colin.fulton@lightspeedsystems.com', 'colin.fulton@lightspeedsystems.com', 'Colin Fulton', 'Strategic Solutions Engineer', NULL, true),
  ('seed:colin.mccabe@lightspeedsystems.com', 'colin.mccabe@lightspeedsystems.com', 'Colin Mccabe', 'General Manager International', NULL, true),
  ('seed:colleen.clark@lightspeedsystems.com', 'colleen.clark@lightspeedsystems.com', 'Colleen Clark', 'Student Safety Specialist', NULL, true),
  ('seed:cristal.cuellar@lightspeedsystems.com', 'cristal.cuellar@lightspeedsystems.com', 'Cristal Cuellar', 'Student Safety Specialist', NULL, true),
  ('seed:daniel.dunn@lightspeedsystems.com', 'daniel.dunn@lightspeedsystems.com', 'Daniel Dunn', 'Strategic Solutions Engineer', NULL, true),
  ('seed:danielle.adams@lightspeedsystems.com', 'danielle.adams@lightspeedsystems.com', 'Danielle Adams', 'Student Safety Specialist', NULL, true),
  ('seed:danielle.rubio@lightspeedsystems.com', 'danielle.rubio@lightspeedsystems.com', 'Danielle Rubio', 'Student Safety Specialist', NULL, true),
  ('seed:dante.munoz@lightspeedsystems.com', 'dante.munoz@lightspeedsystems.com', 'Dante Munoz', 'Solutions Engineer', NULL, true),
  ('seed:december.wilks@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com', 'December Wilks', 'Student Safety Manager', NULL, true),
  ('seed:derek.laurie@lightspeedsystems.com', 'derek.laurie@lightspeedsystems.com', 'Derek Laurie', 'Director Technical Product Management', NULL, true),
  ('seed:dhillon.reddy@lightspeedsystems.com', 'dhillon.reddy@lightspeedsystems.com', 'Dhillon Reddy', 'Intern', NULL, true),
  ('seed:donal.mcmahon@lightspeedsystems.com', 'donal.mcmahon@lightspeedsystems.com', 'Donal Mcmahon', 'Chief AI Officer', 'ELT', true),
  ('seed:douglas.dietert@lightspeedsystems.com', 'douglas.dietert@lightspeedsystems.com', 'Douglas Dietert', 'Orders and Accounts Receivables Specialist', NULL, true),
  ('seed:dylan.claiborne@lightspeedsystems.com', 'dylan.claiborne@lightspeedsystems.com', 'Dylan Claiborne', 'Lead Technical Support Specialist', NULL, true),
  ('seed:emma.stewart@lightspeedsystems.com', 'emma.stewart@lightspeedsystems.com', 'Emma Stewart', 'Intern', NULL, true),
  ('seed:enrique.michel@lightspeedsystems.com', 'enrique.michel@lightspeedsystems.com', 'Enrique Michel', 'Technical Escalation Engineer', NULL, true),
  ('seed:eric.cruz@lightspeedsystems.com', 'eric.cruz@lightspeedsystems.com', 'Eric Cruz', 'Software Engineer', NULL, true),
  ('seed:erika.johnson@lightspeedsystems.com', 'erika.johnson@lightspeedsystems.com', 'Erika Johnson', 'Strategic Account Manager', NULL, true),
  ('seed:esteban.diocares@lightspeedsystems.com', 'esteban.diocares@lightspeedsystems.com', 'Esteban Diocares', 'Site Reliability Engineer', NULL, true),
  ('seed:frank.romero@lightspeedsystems.com', 'frank.romero@lightspeedsystems.com', 'Frank Romero', 'Technical Support Specialist', NULL, true),
  ('seed:gerard.jr.dantel@lightspeedsystems.com', 'gerard.jr.dantel@lightspeedsystems.com', 'Gerard Jr Dantel', 'Senior Director Engineering', NULL, true),
  ('seed:gijo.johny@lightspeedsystems.com', 'gijo.johny@lightspeedsystems.com', 'Gijo Johny', 'Senior QA Automation Engineer', NULL, true),
  ('seed:grace.mellette@lightspeedsystems.com', 'grace.mellette@lightspeedsystems.com', 'Grace Mellette', 'Marketing Coordinator', NULL, true),
  ('seed:gregory.artzt@lightspeedsystems.com', 'gregory.artzt@lightspeedsystems.com', 'Gregory Artzt', 'Senior Director Product Management', NULL, true),
  ('seed:gregory.funk@lightspeedsystems.com', 'gregory.funk@lightspeedsystems.com', 'Gregory Funk', 'VP Corporate Controller', NULL, true),
  ('seed:hadley.james@lightspeedsystems.com', 'hadley.james@lightspeedsystems.com', 'Hadley James', 'Intern', NULL, true),
  ('seed:hailey.thomas@lightspeedsystems.com', 'hailey.thomas@lightspeedsystems.com', 'Hailey Thomas', 'Content Categorization Specialist', NULL, true),
  ('seed:harry.saunders@lightspeedsystems.com', 'harry.saunders@lightspeedsystems.com', 'Harry Saunders', 'Account Manager', NULL, true),
  ('seed:heather.james@lightspeedsystems.com', 'heather.james@lightspeedsystems.com', 'Heather James', 'Director Human Resources', NULL, true),
  ('seed:jack.mcdonnell@lightspeedsystems.com', 'jack.mcdonnell@lightspeedsystems.com', 'Jack Mcdonnell', 'Software Engineer', NULL, true),
  ('seed:jade.friedman@lightspeedsystems.com', 'jade.friedman@lightspeedsystems.com', 'Jade Friedman', 'Intern', NULL, true),
  ('seed:jaeden.richards@lightspeedsystems.com', 'jaeden.richards@lightspeedsystems.com', 'Jaeden Richards', 'Strategic Account Executive', NULL, true),
  ('seed:jai.pandu@lightspeedsystems.com', 'jai.pandu@lightspeedsystems.com', 'Jai Pandu', 'VP Engineering', NULL, true),
  ('seed:jake.bowman@lightspeedsystems.com', 'jake.bowman@lightspeedsystems.com', 'Jake Bowman', 'Financial Analyst', NULL, true),
  ('seed:jake.de.la.garrigue@lightspeedsystems.com', 'jake.de.la.garrigue@lightspeedsystems.com', 'Jake De La Garrigue', 'Associate Account Executive', NULL, true),
  ('seed:james.laprocido@lightspeedsystems.com', 'james.laprocido@lightspeedsystems.com', 'James Laprocido', 'Financial Analyst', NULL, true),
  ('seed:jared.accardo@lightspeedsystems.com', 'jared.accardo@lightspeedsystems.com', 'Jared Accardo', 'VP Product Delivery', NULL, true),
  ('seed:jared.varner@lightspeedsystems.com', 'jared.varner@lightspeedsystems.com', 'Jared Varner', 'Business Analyst', NULL, true),
  ('seed:jason.isaac@lightspeedsystems.com', 'jason.isaac@lightspeedsystems.com', 'Jason Isaac', 'Staff Software Engineer', NULL, true),
  ('seed:jason.montes@lightspeedsystems.com', 'jason.montes@lightspeedsystems.com', 'Jason Montes', 'Student Safety Specialist', NULL, true),
  ('seed:jason.veselka@lightspeedsystems.com', 'jason.veselka@lightspeedsystems.com', 'Jason Veselka', 'Lead Student Safety Specialist', NULL, true),
  ('seed:jeffrey.smith@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com', 'Jeffrey Smith', 'Customer Quality Manager', NULL, true),
  ('seed:jeffrey.zwick@lightspeedsystems.com', 'jeffrey.zwick@lightspeedsystems.com', 'Jeffrey Zwick', 'Senior QA Engineer', NULL, true),
  ('seed:jenisha.karmacharya@lightspeedsystems.com', 'jenisha.karmacharya@lightspeedsystems.com', 'Jenisha Karmacharya', 'Senior QA Automation Engineer', NULL, true),
  ('seed:jennifer.duer@lightspeedsystems.com', 'jennifer.duer@lightspeedsystems.com', 'Jennifer Duer', 'VP, Product Student Success', NULL, true),
  ('seed:jerry.flores@lightspeedsystems.com', 'jerry.flores@lightspeedsystems.com', 'Jerry Flores', 'Student Safety Specialist', NULL, true),
  ('seed:jiana.khazma@lightspeedsystems.com', 'jiana.khazma@lightspeedsystems.com', 'Jiana Khazma', 'Product Marketing Manager', NULL, true),
  ('seed:jide.oke@lightspeedsystems.com', 'jide.oke@lightspeedsystems.com', 'Jide Oke', 'Technical Support Specialist', NULL, true),
  ('seed:joel.walmsley@lightspeedsystems.com', 'joel.walmsley@lightspeedsystems.com', 'Joel Walmsley', 'Solutions Engineer', NULL, true),
  ('seed:john.genter@lightspeedsystems.com', 'john.genter@lightspeedsystems.com', 'John Genter', 'CISO', NULL, true),
  ('seed:jolie.boodansingh@lightspeedsystems.com', 'jolie.boodansingh@lightspeedsystems.com', 'Jolie Boodansingh', 'Student Safety Specialist', NULL, true),
  ('seed:jonathan.adkins@lightspeedsystems.com', 'jonathan.adkins@lightspeedsystems.com', 'Jonathan Adkins', 'Internal Learning & Development Manager', NULL, true),
  ('seed:joseph.decarlo@lightspeedsystems.com', 'joseph.decarlo@lightspeedsystems.com', 'Joseph Decarlo', 'Junior Site Reliability Engineer', NULL, true),
  ('seed:juan.rodriguez.maldonado@lightspeedsystems.com', 'juan.rodriguez.maldonado@lightspeedsystems.com', 'Juan Rodriguez Maldonado', 'Technical Support Specialist', NULL, true),
  ('seed:juliana.morris@lightspeedsystems.com', 'juliana.morris@lightspeedsystems.com', 'Juliana Morris', 'Manager, Contracts', NULL, true),
  ('seed:justin.woolverton@lightspeedsystems.com', 'justin.woolverton@lightspeedsystems.com', 'Justin Woolverton', 'Lead Software Engineer', NULL, true),
  ('seed:katelin.revels@lightspeedsystems.com', 'katelin.revels@lightspeedsystems.com', 'Katelin Revels', 'Student Safety Specialist', NULL, true),
  ('seed:katherine.williamson@lightspeedsystems.com', 'katherine.williamson@lightspeedsystems.com', 'Katherine Williamson', 'Front Office Coordinator/Executive Assistant', NULL, true),
  ('seed:katy.shawcross@lightspeedsystems.com', 'katy.shawcross@lightspeedsystems.com', 'Katy Shawcross', 'Customer Service Representative', NULL, true),
  ('seed:keaton.smith@lightspeedsystems.com', 'keaton.smith@lightspeedsystems.com', 'Keaton Smith', 'Strategic Account Executive', NULL, true),
  ('seed:kenneth.chitwood@lightspeedsystems.com', 'kenneth.chitwood@lightspeedsystems.com', 'Kenneth Chitwood', 'Director Site Reliability', NULL, true),
  ('seed:kevin.askew@lightspeedsystems.com', 'kevin.askew@lightspeedsystems.com', 'Kevin Askew', 'VP Sales', NULL, true),
  ('seed:kevin.chiang@lightspeedsystems.com', 'kevin.chiang@lightspeedsystems.com', 'Kevin Chiang', 'EVP Finance and Corporate Development', NULL, true),
  ('seed:kevin.lasher@lightspeedsystems.com', 'kevin.lasher@lightspeedsystems.com', 'Kevin Lasher', 'Senior Front-End Engineer', NULL, true),
  ('seed:kevin.lawrence@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com', 'Kevin Lawrence', 'EVP, Operations', NULL, true),
  ('seed:khaled.uddin@lightspeedsystems.com', 'khaled.uddin@lightspeedsystems.com', 'Khaled Uddin', 'Technical Support Specialist', NULL, true),
  ('seed:kiah.long@lightspeedsystems.com', 'kiah.long@lightspeedsystems.com', 'Kiah Long', 'Account Manager', NULL, true),
  ('seed:kian.curran@lightspeedsystems.com', 'kian.curran@lightspeedsystems.com', 'Kian Curran', 'Student Safety Specialist', NULL, true),
  ('seed:kirk.orgeldinger@lightspeedsystems.com', 'kirk.orgeldinger@lightspeedsystems.com', 'Kirk Orgeldinger', 'President & CFO', 'ELT', true),
  ('seed:krista.delk@lightspeedsystems.com', 'krista.delk@lightspeedsystems.com', 'Krista Delk', 'Training & Enablement Manager', NULL, true),
  ('seed:kurstye.tillmon@lightspeedsystems.com', 'kurstye.tillmon@lightspeedsystems.com', 'Kurstye Tillmon', 'Senior Student Safety Specialist', NULL, true),
  ('seed:kyle.escobar@lightspeedsystems.com', 'kyle.escobar@lightspeedsystems.com', 'Kyle Escobar', 'Junior QA Engineer', NULL, true),
  ('seed:kyle.olson@lightspeedsystems.com', 'kyle.olson@lightspeedsystems.com', 'Kyle Olson', 'Business Development Representative', NULL, true),
  ('seed:larissa.negreiros.somaio@lightspeedsystems.com', 'larissa.negreiros.somaio@lightspeedsystems.com', 'Larissa Negreiros Somaio', 'Senior Product Marketing Manager', NULL, true),
  ('seed:lauren.mcnair@lightspeedsystems.com', 'lauren.mcnair@lightspeedsystems.com', 'Lauren Mcnair', 'Strategic Account Manager', NULL, true),
  ('seed:leigh.morris@lightspeedsystems.com', 'leigh.morris@lightspeedsystems.com', 'Leigh Morris', 'Technical Product Manager', NULL, true),
  ('seed:lewis.brown@lightspeedsystems.com', 'lewis.brown@lightspeedsystems.com', 'Lewis Brown', 'Technical Support Specialist', NULL, true),
  ('seed:liam.roberts@lightspeedsystems.com', 'liam.roberts@lightspeedsystems.com', 'Liam Roberts', 'International Marketing Manager', NULL, true),
  ('seed:lillian.fox@lightspeedsystems.com', 'lillian.fox@lightspeedsystems.com', 'Lillian Fox', 'Intern', NULL, true),
  ('seed:luke.shearin@lightspeedsystems.com', 'luke.shearin@lightspeedsystems.com', 'Luke Shearin', 'Team Lead, Revenue Operations', NULL, true),
  ('seed:lydell.craig@lightspeedsystems.com', 'lydell.craig@lightspeedsystems.com', 'Lydell Craig', 'Student Safety Specialist', NULL, true),
  ('seed:madelyne.stewart@lightspeedsystems.com', 'madelyne.stewart@lightspeedsystems.com', 'Madelyne Stewart', 'Events Manager', NULL, true),
  ('seed:madhuri.balasubramanya@lightspeedsystems.com', 'madhuri.balasubramanya@lightspeedsystems.com', 'Madhuri Balasubramanya', 'QA Engineer', NULL, true),
  ('seed:marcos.suarez@lightspeedsystems.com', 'marcos.suarez@lightspeedsystems.com', 'Marcos Suarez', 'Marketing Manager', NULL, true),
  ('seed:marie.wittry@lightspeedsystems.com', 'marie.wittry@lightspeedsystems.com', 'Marie Wittry', 'Technical Support Specialist', NULL, true),
  ('seed:marlisa.mungo@lightspeedsystems.com', 'marlisa.mungo@lightspeedsystems.com', 'Marlisa Mungo', 'Student Safety Specialist', NULL, true),
  ('seed:matthew.ames@lightspeedsystems.com', 'matthew.ames@lightspeedsystems.com', 'Matthew Ames', 'Junior Software Engineer', NULL, true),
  ('seed:matthew.burg@lightspeedsystems.com', 'matthew.burg@lightspeedsystems.com', 'Matthew Burg', 'VP, Product IT Solutions', NULL, true),
  ('seed:matthew.nelson@lightspeedsystems.com', 'matthew.nelson@lightspeedsystems.com', 'Matthew Nelson', 'Strategic Solutions Engineer', NULL, true),
  ('seed:megan.black@lightspeedsystems.com', 'megan.black@lightspeedsystems.com', 'Megan Black', 'International Marketing Coordinator', NULL, true),
  ('seed:megan.duhon@lightspeedsystems.com', 'megan.duhon@lightspeedsystems.com', 'Megan Duhon', 'Senior Accountant', NULL, true),
  ('seed:michael.boggess@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com', 'Michael Boggess', 'VP Sales', NULL, true),
  ('seed:michael.durando@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com', 'Michael Durando', 'VP Sales', NULL, true),
  ('seed:michael.roddey@lightspeedsystems.com', 'michael.roddey@lightspeedsystems.com', 'Michael Roddey', 'Strategic Account Manager', NULL, true),
  ('seed:michael.waszazak@lightspeedsystems.com', 'michael.waszazak@lightspeedsystems.com', 'Michael Waszazak', 'Manager Product Design', NULL, true),
  ('seed:michelle.mcgovern@lightspeedsystems.com', 'michelle.mcgovern@lightspeedsystems.com', 'Michelle Mcgovern', 'Technical Product Manager', NULL, true),
  ('seed:michelle.vargas@lightspeedsystems.com', 'michelle.vargas@lightspeedsystems.com', 'Michelle Vargas', 'Lead QA Engineer', NULL, true),
  ('seed:mitchell.laurrenring@lightspeedsystems.com', 'mitchell.laurrenring@lightspeedsystems.com', 'Mitchell Laurren-Ring', 'Staff Software Engineer', NULL, true),
  ('seed:morgan.canales@lightspeedsystems.com', 'morgan.canales@lightspeedsystems.com', 'Morgan Canales', 'Human Resources Business Partner', NULL, true),
  ('seed:nathan.davila@lightspeedsystems.com', 'nathan.davila@lightspeedsystems.com', 'Nathan Davila', 'Student Safety Specialist', NULL, true),
  ('seed:nathan.estrada@lightspeedsystems.com', 'nathan.estrada@lightspeedsystems.com', 'Nathan Estrada', 'Student Safety Specialist', NULL, true),
  ('seed:nathan.johnson@lightspeedsystems.com', 'nathan.johnson@lightspeedsystems.com', 'Nathan Johnson', 'Senior Staff Software Engineer', NULL, true),
  ('seed:neil.shaw@lightspeedsystems.com', 'neil.shaw@lightspeedsystems.com', 'Neil Shaw', 'Senior Software Engineer', NULL, true),
  ('seed:nicholas.chambers@lightspeedsystems.com', 'nicholas.chambers@lightspeedsystems.com', 'Nicholas Chambers', 'QA Engineer', NULL, true),
  ('seed:nicholas.zema@lightspeedsystems.com', 'nicholas.zema@lightspeedsystems.com', 'Nicholas Zema', 'Strategic Account Executive', NULL, true),
  ('seed:nicole.greig@lightspeedsystems.com', 'nicole.greig@lightspeedsystems.com', 'Nicole Greig', 'Associate Account Manager', NULL, true),
  ('seed:nicole.tribo@lightspeedsystems.com', 'nicole.tribo@lightspeedsystems.com', 'Nicole Tribo', 'Renewals Specialist', NULL, true),
  ('seed:niels.dhollanderbarclay@lightspeedsystems.com', 'niels.dhollanderbarclay@lightspeedsystems.com', 'Niels Dhollander-Barclay', 'Senior Data Engineer', NULL, true),
  ('seed:nykayla.carter@lightspeedsystems.com', 'nykayla.carter@lightspeedsystems.com', 'Nykayla Carter', 'Senior Student Safety Specialist', NULL, true),
  ('seed:olivia.gibbons@lightspeedsystems.com', 'olivia.gibbons@lightspeedsystems.com', 'Olivia Gibbons', 'Intern', NULL, true),
  ('seed:patrick.chapa@lightspeedsystems.com', 'patrick.chapa@lightspeedsystems.com', 'Patrick Chapa', 'Senior Director MIS', NULL, true),
  ('seed:paul.chapa@lightspeedsystems.com', 'paul.chapa@lightspeedsystems.com', 'Paul Chapa', 'Intern', NULL, true),
  ('seed:perry.sittser@lightspeedsystems.com', 'perry.sittser@lightspeedsystems.com', 'Perry Sittser', 'Lead Software Engineer', NULL, true),
  ('seed:preston.matheson@lightspeedsystems.com', 'preston.matheson@lightspeedsystems.com', 'Preston Matheson', 'Lead Software Engineer', NULL, true),
  ('seed:quinten.oldaker@lightspeedsystems.com', 'quinten.oldaker@lightspeedsystems.com', 'Quinten Oldaker', 'Solutions Engineer', NULL, true),
  ('seed:rachel.thompson@lightspeedsystems.com', 'rachel.thompson@lightspeedsystems.com', 'Rachel Thompson', 'Senior Director Revenue Operations', NULL, true),
  ('seed:ramy.sahouri@lightspeedsystems.com', 'ramy.sahouri@lightspeedsystems.com', 'Ramy Sahouri', 'Solutions Engineer', NULL, true),
  ('seed:rashida.brown@lightspeedsystems.com', 'rashida.brown@lightspeedsystems.com', 'Rashida Brown', 'Student Safety Specialist', NULL, true),
  ('seed:rebecca.gould@lightspeedsystems.com', 'rebecca.gould@lightspeedsystems.com', 'Rebecca Gould', 'Principal Technical Product Manager', NULL, true),
  ('seed:richard.chown@lightspeedsystems.com', 'richard.chown@lightspeedsystems.com', 'Richard Chown', 'Manager, Strategic Solutions Engineering', NULL, true),
  ('seed:ricky.salter@lightspeedsystems.com', 'ricky.salter@lightspeedsystems.com', 'Ricky Salter', 'Student Safety Manager', NULL, true),
  ('seed:robert.bruce@lightspeedsystems.com', 'robert.bruce@lightspeedsystems.com', 'Robert Bruce', 'Lead Software Engineer', NULL, true),
  ('seed:robert.hancock@lightspeedsystems.com', 'robert.hancock@lightspeedsystems.com', 'Robert Hancock', 'Strategic Solutions Engineer', NULL, true),
  ('seed:robert.mccartney@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com', 'Robert Mccartney', 'Senior Director Solutions Engineering & Support', NULL, true),
  ('seed:robert.mcmillan@lightspeedsystems.com', 'robert.mcmillan@lightspeedsystems.com', 'Robert Mcmillan', 'Chief Technology Officer', 'ELT', true),
  ('seed:ross.mcaden@lightspeedsystems.com', 'ross.mcaden@lightspeedsystems.com', 'Ross Mcaden', 'Strategic Account Manager', NULL, true),
  ('seed:ryan.bond@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com', 'Ryan Bond', 'VP Engineering', NULL, true),
  ('seed:ryan.oglesby@lightspeedsystems.com', 'ryan.oglesby@lightspeedsystems.com', 'Ryan Oglesby', 'Site Reliability Engineer', NULL, true),
  ('seed:ryan.passanisi@lightspeedsystems.com', 'ryan.passanisi@lightspeedsystems.com', 'Ryan Passanisi', 'Junior AI Automation Engineer', NULL, true),
  ('seed:ryan.stufflebeam@lightspeedsystems.com', 'ryan.stufflebeam@lightspeedsystems.com', 'Ryan Stufflebeam', 'Senior Technical Escalation Engineer', NULL, true),
  ('seed:sabrina.drouin@lightspeedsystems.com', 'sabrina.drouin@lightspeedsystems.com', 'Sabrina Drouin', 'Junior Contracts Administrator', NULL, true),
  ('seed:sam.howard.mr@lightspeedsystems.com', 'sam.howard.mr@lightspeedsystems.com', 'Sam Howard Mr', 'Strategic Account Executive', NULL, true),
  ('seed:samantha.revels@lightspeedsystems.com', 'samantha.revels@lightspeedsystems.com', 'Samantha Revels', 'Training & Enablement Manager', NULL, true),
  ('seed:saul.trejo@lightspeedsystems.com', 'saul.trejo@lightspeedsystems.com', 'Saul Trejo', 'Customer Service Representative', NULL, true),
  ('seed:scott.dunham@lightspeedsystems.com', 'scott.dunham@lightspeedsystems.com', 'Scott Dunham', 'Manager Finance', NULL, true),
  ('seed:scott.meeks@lightspeedsystems.com', 'scott.meeks@lightspeedsystems.com', 'Scott Meeks', 'Senior Strategic Account Executive', NULL, true),
  ('seed:sergio.villegas@lightspeedsystems.com', 'sergio.villegas@lightspeedsystems.com', 'Sergio Villegas', 'Strategic Account Executive', NULL, true),
  ('seed:shad.mcgaha@lightspeedsystems.com', 'shad.mcgaha@lightspeedsystems.com', 'Shad Mcgaha', 'Senior Strategic Solutions Engineer', NULL, true),
  ('seed:shakira.romero@lightspeedsystems.com', 'shakira.romero@lightspeedsystems.com', 'Shakira Romero', 'Student Safety Specialist', NULL, true),
  ('seed:shanna.johnson@lightspeedsystems.com', 'shanna.johnson@lightspeedsystems.com', 'Shanna Johnson', 'Student Safety Specialist', NULL, true),
  ('seed:shaun.phillips@lightspeedsystems.com', 'shaun.phillips@lightspeedsystems.com', 'Shaun Phillips', 'Acting Director of Sales EMEIA', NULL, true),
  ('seed:sinead.williams@lightspeedsystems.com', 'sinead.williams@lightspeedsystems.com', 'Sinead Williams', 'Senior Student Safety Specialist', NULL, true),
  ('seed:spencer.smith@lightspeedsystems.com', 'spencer.smith@lightspeedsystems.com', 'Spencer Smith', 'Account Executive', NULL, true),
  ('seed:steven.landwehr@lightspeedsystems.com', 'steven.landwehr@lightspeedsystems.com', 'Steven Landwehr', 'Senior Software Engineer', NULL, true),
  ('seed:steven.miller.junior@lightspeedsystems.com', 'steven.miller.junior@lightspeedsystems.com', 'Steven Miller Junior', 'Senior AI Automation Engineer', NULL, true),
  ('seed:syed.muhammad.hassaan.gillani@lightspeedsystems.com', 'syed.muhammad.hassaan.gillani@lightspeedsystems.com', 'Syed Muhammad Hassaan Gillani', 'Associate Technical Support Specialist', NULL, true),
  ('seed:tameka.smith@lightspeedsystems.com', 'tameka.smith@lightspeedsystems.com', 'Tameka Smith', 'Student Safety Specialist', NULL, true),
  ('seed:tania.mackie.mrs@lightspeedsystems.com', 'tania.mackie.mrs@lightspeedsystems.com', 'Tania Mackie Mrs', 'Director International Safeguarding & Digital Transformation', NULL, true),
  ('seed:teresa.reuter@lightspeedsystems.com', 'teresa.reuter@lightspeedsystems.com', 'Teresa Reuter', 'Senior Director Customer Operations', NULL, true),
  ('seed:thayer.kacher@lightspeedsystems.com', 'thayer.kacher@lightspeedsystems.com', 'Thayer Kacher', 'Intern', NULL, true),
  ('seed:tichiere.womble@lightspeedsystems.com', 'tichiere.womble@lightspeedsystems.com', 'Tichiere Womble', 'Lead Student Safety Specialist', NULL, true),
  ('seed:tracy.craig@lightspeedsystems.com', 'tracy.craig@lightspeedsystems.com', 'Tracy Craig', 'Student Safety Manager', NULL, true),
  ('seed:travis.bullock@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com', 'Travis Bullock', 'Technical Support Manager', NULL, true),
  ('seed:trevor.davis@lightspeedsystems.com', 'trevor.davis@lightspeedsystems.com', 'Trevor Davis', 'Strategic Solutions Engineer', NULL, true),
  ('seed:trung.pham@lightspeedsystems.com', 'trung.pham@lightspeedsystems.com', 'Trung Pham', 'Lead QA Automation Engineer', NULL, true),
  ('seed:tu.ngo@lightspeedsystems.com', 'tu.ngo@lightspeedsystems.com', 'Tu Ngo', 'Associate Technical Support Specialist', NULL, true),
  ('seed:van.mualcin@lightspeedsystems.com', 'van.mualcin@lightspeedsystems.com', 'Van Mualcin', 'Lead Senior Software Engineer', NULL, true),
  ('seed:vernie.ogden@lightspeedsystems.com', 'vernie.ogden@lightspeedsystems.com', 'Vernie Ogden', 'Technical Product Manager', NULL, true),
  ('seed:wengel.huluka@lightspeedsystems.com', 'wengel.huluka@lightspeedsystems.com', 'Wengel Huluka', 'Front-End Engineer', NULL, true),
  ('seed:wesley.cunningham@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com', 'Wesley Cunningham', 'Senior Manager, Solutions Engineering', NULL, true),
  ('seed:whitney.veatch@lightspeedsystems.com', 'whitney.veatch@lightspeedsystems.com', 'Whitney Veatch', 'Senior Student Safety Specialist', NULL, true),
  ('seed:william.hellemsmoody@lightspeedsystems.com', 'william.hellemsmoody@lightspeedsystems.com', 'William Hellems-Moody', 'Systems Administrator', NULL, true),
  ('seed:william.long@lightspeedsystems.com', 'william.long@lightspeedsystems.com', 'William Long', 'Manager, Strategic Solutions Engineering', NULL, true),
  ('seed:wing.mar@lightspeedsystems.com', 'wing.mar@lightspeedsystems.com', 'Wing Mar', 'Senior Technical Support Specialist', NULL, true),
  ('seed:winter.rhoden@lightspeedsystems.com', 'winter.rhoden@lightspeedsystems.com', 'Winter Rhoden', 'Intern', NULL, true),
  ('seed:zachary.horn@lightspeedsystems.com', 'zachary.horn@lightspeedsystems.com', 'Zachary Horn', 'Director of Strategic Programs', NULL, true),
  ('seed:zakkiyya.purnell@lightspeedsystems.com', 'zakkiyya.purnell@lightspeedsystems.com', 'Zakkiyya Purnell', 'Senior Student Safety Specialist', NULL, true)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name, title = EXCLUDED.title,
  leader_badge = EXCLUDED.leader_badge, is_active = true, updated_at = now();
--> statement-breakpoint

-- 3) Wire reporting lines (child.manager_id = parent.id).
UPDATE users c SET manager_id = p.id, updated_at = now()
FROM (VALUES
  ('abraham.ybarra@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('adrian.rios.alvarez@lightspeedsystems.com', 'patrick.chapa@lightspeedsystems.com'),
  ('adrienne.synos@lightspeedsystems.com', 'gregory.funk@lightspeedsystems.com'),
  ('aiyana.mathew@lightspeedsystems.com', 'jai.pandu@lightspeedsystems.com'),
  ('albert.garcia@lightspeedsystems.com', 'tracy.craig@lightspeedsystems.com'),
  ('alecia.boggess@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com'),
  ('alex.wade@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com'),
  ('alexander.crouse@lightspeedsystems.com', 'bradley.rowe@lightspeedsystems.com'),
  ('alexander.doria@lightspeedsystems.com', 'brian.truong@lightspeedsystems.com'),
  ('alexander.hesse@lightspeedsystems.com', 'patrick.chapa@lightspeedsystems.com'),
  ('alexander.sands@lightspeedsystems.com', 'charles.bryant@lightspeedsystems.com'),
  ('alexander.szabo@lightspeedsystems.com', 'caitlin.mcdermott@lightspeedsystems.com'),
  ('alexander.woods@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com'),
  ('alyssa.ann.silva@lightspeedsystems.com', 'alyssa.russo@lightspeedsystems.com'),
  ('alyssa.russo@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('amanda.gorena@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com'),
  ('amy.bennett@lightspeedsystems.com', 'brian.thomas@lightspeedsystems.com'),
  ('andrew.cribari@lightspeedsystems.com', 'rebecca.gould@lightspeedsystems.com'),
  ('andrew.fowler@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com'),
  ('andrew.hecht@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com'),
  ('andy.bennetta@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com'),
  ('angela.mazza@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('anita.krueger@lightspeedsystems.com', 'kenneth.chitwood@lightspeedsystems.com'),
  ('ann.marie.martinez@lightspeedsystems.com', 'kevin.askew@lightspeedsystems.com'),
  ('armahn.turk@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('austin.sweet@lightspeedsystems.com', 'charles.bryant@lightspeedsystems.com'),
  ('ava.friloux@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com'),
  ('benjamin.thomas@lightspeedsystems.com', 'steven.miller.junior@lightspeedsystems.com'),
  ('bradley.rowe@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com'),
  ('bradley.white@lightspeedsystems.com', 'john.genter@lightspeedsystems.com'),
  ('braedon.mulder@lightspeedsystems.com', 'aiyana.mathew@lightspeedsystems.com'),
  ('brandon.jones@lightspeedsystems.com', 'derek.laurie@lightspeedsystems.com'),
  ('brian.truong@lightspeedsystems.com', 'kenneth.chitwood@lightspeedsystems.com'),
  ('brock.anderson@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('brock.meadors@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com'),
  ('brooke.brown@lightspeedsystems.com', 'teresa.reuter@lightspeedsystems.com'),
  ('brooke.friedman@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('bryan.anderson@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com'),
  ('bryan.steele@lightspeedsystems.com', 'michael.waszazak@lightspeedsystems.com'),
  ('caitlin.mcdermott@lightspeedsystems.com', 'jennifer.duer@lightspeedsystems.com'),
  ('cameron.meyer@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com'),
  ('carl.ahlstrand@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com'),
  ('casey.butera@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com'),
  ('casey.hann@lightspeedsystems.com', 'teresa.reuter@lightspeedsystems.com'),
  ('charles.bryant@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com'),
  ('charushila.awhad@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com'),
  ('chase.masiel@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com'),
  ('chasity.lyson@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com'),
  ('christian.trahan@lightspeedsystems.com', 'brian.truong@lightspeedsystems.com'),
  ('christina.atkinson@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com'),
  ('christina.mares@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('christopher.dunn@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com'),
  ('christopher.newkirk@lightspeedsystems.com', 'kenneth.chitwood@lightspeedsystems.com'),
  ('christopher.spink@lightspeedsystems.com', 'shaun.phillips@lightspeedsystems.com'),
  ('christopher.travis@lightspeedsystems.com', 'brian.thomas@lightspeedsystems.com'),
  ('cindy.moore@lightspeedsystems.com', 'teresa.reuter@lightspeedsystems.com'),
  ('colin.fulton@lightspeedsystems.com', 'richard.chown@lightspeedsystems.com'),
  ('colin.mccabe@lightspeedsystems.com', 'christopher.travis@lightspeedsystems.com'),
  ('colleen.clark@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('cristal.cuellar@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('daniel.dunn@lightspeedsystems.com', 'charles.bryant@lightspeedsystems.com'),
  ('danielle.adams@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('danielle.rubio@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('dante.munoz@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com'),
  ('december.wilks@lightspeedsystems.com', 'brock.anderson@lightspeedsystems.com'),
  ('derek.laurie@lightspeedsystems.com', 'jared.accardo@lightspeedsystems.com'),
  ('dhillon.reddy@lightspeedsystems.com', 'scott.dunham@lightspeedsystems.com'),
  ('donal.mcmahon@lightspeedsystems.com', 'brian.thomas@lightspeedsystems.com'),
  ('douglas.dietert@lightspeedsystems.com', 'adrienne.synos@lightspeedsystems.com'),
  ('dylan.claiborne@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('emma.stewart@lightspeedsystems.com', 'larissa.negreiros.somaio@lightspeedsystems.com'),
  ('enrique.michel@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com'),
  ('eric.cruz@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com'),
  ('erika.johnson@lightspeedsystems.com', 'kevin.askew@lightspeedsystems.com'),
  ('esteban.diocares@lightspeedsystems.com', 'kenneth.chitwood@lightspeedsystems.com'),
  ('frank.romero@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('gerard.jr.dantel@lightspeedsystems.com', 'jai.pandu@lightspeedsystems.com'),
  ('gijo.johny@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com'),
  ('grace.mellette@lightspeedsystems.com', 'amanda.gorena@lightspeedsystems.com'),
  ('gregory.artzt@lightspeedsystems.com', 'jennifer.duer@lightspeedsystems.com'),
  ('gregory.funk@lightspeedsystems.com', 'kevin.chiang@lightspeedsystems.com'),
  ('hadley.james@lightspeedsystems.com', 'michael.waszazak@lightspeedsystems.com'),
  ('hailey.thomas@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com'),
  ('harry.saunders@lightspeedsystems.com', 'shaun.phillips@lightspeedsystems.com'),
  ('heather.james@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('jack.mcdonnell@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com'),
  ('jade.friedman@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('jaeden.richards@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com'),
  ('jai.pandu@lightspeedsystems.com', 'robert.mcmillan@lightspeedsystems.com'),
  ('jake.bowman@lightspeedsystems.com', 'scott.dunham@lightspeedsystems.com'),
  ('jake.de.la.garrigue@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com'),
  ('james.laprocido@lightspeedsystems.com', 'scott.dunham@lightspeedsystems.com'),
  ('jared.accardo@lightspeedsystems.com', 'robert.mcmillan@lightspeedsystems.com'),
  ('jared.varner@lightspeedsystems.com', 'matthew.burg@lightspeedsystems.com'),
  ('jason.isaac@lightspeedsystems.com', 'brock.meadors@lightspeedsystems.com'),
  ('jason.montes@lightspeedsystems.com', 'ricky.salter@lightspeedsystems.com'),
  ('jason.veselka@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('jeffrey.smith@lightspeedsystems.com', 'jared.accardo@lightspeedsystems.com'),
  ('jeffrey.zwick@lightspeedsystems.com', 'derek.laurie@lightspeedsystems.com'),
  ('jenisha.karmacharya@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com'),
  ('jennifer.duer@lightspeedsystems.com', 'robert.mcmillan@lightspeedsystems.com'),
  ('jerry.flores@lightspeedsystems.com', 'tracy.craig@lightspeedsystems.com'),
  ('jiana.khazma@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com'),
  ('jide.oke@lightspeedsystems.com', 'andy.bennetta@lightspeedsystems.com'),
  ('joel.walmsley@lightspeedsystems.com', 'richard.chown@lightspeedsystems.com'),
  ('john.genter@lightspeedsystems.com', 'robert.mcmillan@lightspeedsystems.com'),
  ('jolie.boodansingh@lightspeedsystems.com', 'ricky.salter@lightspeedsystems.com'),
  ('jonathan.adkins@lightspeedsystems.com', 'brock.anderson@lightspeedsystems.com'),
  ('joseph.decarlo@lightspeedsystems.com', 'kenneth.chitwood@lightspeedsystems.com'),
  ('juan.rodriguez.maldonado@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('juliana.morris@lightspeedsystems.com', 'gregory.funk@lightspeedsystems.com'),
  ('justin.woolverton@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com'),
  ('katelin.revels@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('katherine.williamson@lightspeedsystems.com', 'kirk.orgeldinger@lightspeedsystems.com'),
  ('katy.shawcross@lightspeedsystems.com', 'andy.bennetta@lightspeedsystems.com'),
  ('keaton.smith@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com'),
  ('kenneth.chitwood@lightspeedsystems.com', 'robert.mcmillan@lightspeedsystems.com'),
  ('kevin.askew@lightspeedsystems.com', 'christopher.travis@lightspeedsystems.com'),
  ('kevin.chiang@lightspeedsystems.com', 'kirk.orgeldinger@lightspeedsystems.com'),
  ('kevin.lasher@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com'),
  ('kevin.lawrence@lightspeedsystems.com', 'kirk.orgeldinger@lightspeedsystems.com'),
  ('khaled.uddin@lightspeedsystems.com', 'andy.bennetta@lightspeedsystems.com'),
  ('kiah.long@lightspeedsystems.com', 'colin.mccabe@lightspeedsystems.com'),
  ('kian.curran@lightspeedsystems.com', 'ricky.salter@lightspeedsystems.com'),
  ('kirk.orgeldinger@lightspeedsystems.com', 'brian.thomas@lightspeedsystems.com'),
  ('krista.delk@lightspeedsystems.com', 'teresa.reuter@lightspeedsystems.com'),
  ('kurstye.tillmon@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('kyle.escobar@lightspeedsystems.com', 'michelle.mcgovern@lightspeedsystems.com'),
  ('kyle.olson@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com'),
  ('larissa.negreiros.somaio@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com'),
  ('lauren.mcnair@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com'),
  ('leigh.morris@lightspeedsystems.com', 'jared.accardo@lightspeedsystems.com'),
  ('lewis.brown@lightspeedsystems.com', 'andy.bennetta@lightspeedsystems.com'),
  ('liam.roberts@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com'),
  ('lillian.fox@lightspeedsystems.com', 'heather.james@lightspeedsystems.com'),
  ('luke.shearin@lightspeedsystems.com', 'kevin.chiang@lightspeedsystems.com'),
  ('lydell.craig@lightspeedsystems.com', 'ricky.salter@lightspeedsystems.com'),
  ('madelyne.stewart@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com'),
  ('madhuri.balasubramanya@lightspeedsystems.com', 'vernie.ogden@lightspeedsystems.com'),
  ('marcos.suarez@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com'),
  ('marie.wittry@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('marlisa.mungo@lightspeedsystems.com', 'tracy.craig@lightspeedsystems.com'),
  ('matthew.ames@lightspeedsystems.com', 'kenneth.chitwood@lightspeedsystems.com'),
  ('matthew.burg@lightspeedsystems.com', 'jennifer.duer@lightspeedsystems.com'),
  ('matthew.nelson@lightspeedsystems.com', 'charles.bryant@lightspeedsystems.com'),
  ('megan.black@lightspeedsystems.com', 'liam.roberts@lightspeedsystems.com'),
  ('megan.duhon@lightspeedsystems.com', 'adrienne.synos@lightspeedsystems.com'),
  ('michael.boggess@lightspeedsystems.com', 'christopher.travis@lightspeedsystems.com'),
  ('michael.durando@lightspeedsystems.com', 'christopher.travis@lightspeedsystems.com'),
  ('michael.roddey@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com'),
  ('michael.waszazak@lightspeedsystems.com', 'jennifer.duer@lightspeedsystems.com'),
  ('michelle.mcgovern@lightspeedsystems.com', 'jared.accardo@lightspeedsystems.com'),
  ('michelle.vargas@lightspeedsystems.com', 'vernie.ogden@lightspeedsystems.com'),
  ('mitchell.laurrenring@lightspeedsystems.com', 'brock.meadors@lightspeedsystems.com'),
  ('morgan.canales@lightspeedsystems.com', 'heather.james@lightspeedsystems.com'),
  ('nathan.davila@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('nathan.estrada@lightspeedsystems.com', 'ricky.salter@lightspeedsystems.com'),
  ('nathan.johnson@lightspeedsystems.com', 'brock.meadors@lightspeedsystems.com'),
  ('neil.shaw@lightspeedsystems.com', 'brock.meadors@lightspeedsystems.com'),
  ('nicholas.chambers@lightspeedsystems.com', 'rebecca.gould@lightspeedsystems.com'),
  ('nicholas.zema@lightspeedsystems.com', 'kevin.askew@lightspeedsystems.com'),
  ('nicole.greig@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com'),
  ('nicole.tribo@lightspeedsystems.com', 'teresa.reuter@lightspeedsystems.com'),
  ('niels.dhollanderbarclay@lightspeedsystems.com', 'brian.truong@lightspeedsystems.com'),
  ('nykayla.carter@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('olivia.gibbons@lightspeedsystems.com', 'larissa.negreiros.somaio@lightspeedsystems.com'),
  ('patrick.chapa@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('paul.chapa@lightspeedsystems.com', 'patrick.chapa@lightspeedsystems.com'),
  ('perry.sittser@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com'),
  ('preston.matheson@lightspeedsystems.com', 'ryan.bond@lightspeedsystems.com'),
  ('quinten.oldaker@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com'),
  ('rachel.thompson@lightspeedsystems.com', 'christopher.travis@lightspeedsystems.com'),
  ('ramy.sahouri@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com'),
  ('rashida.brown@lightspeedsystems.com', 'ricky.salter@lightspeedsystems.com'),
  ('rebecca.gould@lightspeedsystems.com', 'jared.accardo@lightspeedsystems.com'),
  ('richard.chown@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com'),
  ('ricky.salter@lightspeedsystems.com', 'brock.anderson@lightspeedsystems.com'),
  ('robert.bruce@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com'),
  ('robert.hancock@lightspeedsystems.com', 'bradley.rowe@lightspeedsystems.com'),
  ('robert.mccartney@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('robert.mcmillan@lightspeedsystems.com', 'brian.thomas@lightspeedsystems.com'),
  ('ross.mcaden@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com'),
  ('ryan.bond@lightspeedsystems.com', 'robert.mcmillan@lightspeedsystems.com'),
  ('ryan.oglesby@lightspeedsystems.com', 'kenneth.chitwood@lightspeedsystems.com'),
  ('ryan.passanisi@lightspeedsystems.com', 'donal.mcmahon@lightspeedsystems.com'),
  ('ryan.stufflebeam@lightspeedsystems.com', 'wesley.cunningham@lightspeedsystems.com'),
  ('sabrina.drouin@lightspeedsystems.com', 'juliana.morris@lightspeedsystems.com'),
  ('sam.howard.mr@lightspeedsystems.com', 'shaun.phillips@lightspeedsystems.com'),
  ('samantha.revels@lightspeedsystems.com', 'teresa.reuter@lightspeedsystems.com'),
  ('saul.trejo@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('scott.dunham@lightspeedsystems.com', 'kevin.chiang@lightspeedsystems.com'),
  ('scott.meeks@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com'),
  ('sergio.villegas@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com'),
  ('shad.mcgaha@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com'),
  ('shakira.romero@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('shanna.johnson@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('shaun.phillips@lightspeedsystems.com', 'colin.mccabe@lightspeedsystems.com'),
  ('sinead.williams@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('spencer.smith@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com'),
  ('steven.landwehr@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com'),
  ('steven.miller.junior@lightspeedsystems.com', 'donal.mcmahon@lightspeedsystems.com'),
  ('syed.muhammad.hassaan.gillani@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('tameka.smith@lightspeedsystems.com', 'tracy.craig@lightspeedsystems.com'),
  ('tania.mackie.mrs@lightspeedsystems.com', 'colin.mccabe@lightspeedsystems.com'),
  ('teresa.reuter@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('thayer.kacher@lightspeedsystems.com', 'adrienne.synos@lightspeedsystems.com'),
  ('tichiere.womble@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com'),
  ('tracy.craig@lightspeedsystems.com', 'brock.anderson@lightspeedsystems.com'),
  ('travis.bullock@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com'),
  ('trevor.davis@lightspeedsystems.com', 'bradley.rowe@lightspeedsystems.com'),
  ('trung.pham@lightspeedsystems.com', 'jeffrey.smith@lightspeedsystems.com'),
  ('tu.ngo@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('van.mualcin@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com'),
  ('vernie.ogden@lightspeedsystems.com', 'jared.accardo@lightspeedsystems.com'),
  ('wengel.huluka@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com'),
  ('wesley.cunningham@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com'),
  ('whitney.veatch@lightspeedsystems.com', 'tracy.craig@lightspeedsystems.com'),
  ('william.hellemsmoody@lightspeedsystems.com', 'patrick.chapa@lightspeedsystems.com'),
  ('william.long@lightspeedsystems.com', 'robert.mccartney@lightspeedsystems.com'),
  ('wing.mar@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com'),
  ('winter.rhoden@lightspeedsystems.com', 'john.genter@lightspeedsystems.com'),
  ('zachary.horn@lightspeedsystems.com', 'kevin.lawrence@lightspeedsystems.com'),
  ('zakkiyya.purnell@lightspeedsystems.com', 'december.wilks@lightspeedsystems.com')
) AS m(child_email, parent_email)
JOIN users p ON p.email = m.parent_email
WHERE c.email = m.child_email;
--> statement-breakpoint

-- 4) CEO sits at the top.
UPDATE users SET manager_id = NULL, updated_at = now() WHERE email = 'brian.thomas@lightspeedsystems.com';
