-- 0024 Feed the official chart's departments + titles into the managed
-- lookups (departments, job_titles) and link every person's department_id and
-- job_title_id, so the Org tree shows departments and the admin Title/Dept
-- dropdowns reflect each person. Idempotent: ON CONFLICT(name/title) DO NOTHING
-- + set-based FK backfill. Source: official org chart (0023).

-- 1) Departments (add any missing; keep existing).
INSERT INTO "departments" ("name", "sort_order") VALUES
  ('Administration', 100),
  ('Content Categorization', 110),
  ('Customer Service', 120),
  ('Customer Success', 130),
  ('Customer Success Engineering', 140),
  ('Data Science', 150),
  ('Finance', 160),
  ('Human Resource', 170),
  ('MIS', 180),
  ('Marketing', 190),
  ('Product Development', 200),
  ('Product Management', 210),
  ('Product Marketing', 220),
  ('QAT', 230),
  ('Sales', 240),
  ('Sales Engineers', 250),
  ('Sales Operations', 260),
  ('Scrum', 270),
  ('Security and Compliance', 280),
  ('Security and Hosting', 290),
  ('Student Safety', 300)
ON CONFLICT ("name") DO NOTHING;
--> statement-breakpoint

-- 2) Job titles (add any missing; keep existing).
INSERT INTO "job_titles" ("title", "sort_order") VALUES
  ('Account Executive', 100),
  ('Account Manager', 110),
  ('Acting Director of Sales EMEIA', 120),
  ('Associate Account Executive', 130),
  ('Associate Account Manager', 140),
  ('Associate Technical Product Manager', 150),
  ('Associate Technical Support Specialist', 160),
  ('Business Analyst', 170),
  ('Business Development Representative', 180),
  ('CEO & Founder', 190),
  ('CISO', 200),
  ('Chief AI Officer', 210),
  ('Chief Revenue Officer', 220),
  ('Chief Technology Officer', 230),
  ('Chief of Staff', 240),
  ('Content Categorization Specialist', 250),
  ('Customer Operations Analyst', 260),
  ('Customer Quality Manager', 270),
  ('Customer Service Representative', 280),
  ('Data Platform Manager', 290),
  ('Director Corporate Marketing', 300),
  ('Director Human Resources', 310),
  ('Director International Safeguarding & Digital Transformation', 320),
  ('Director Site Reliability', 330),
  ('Director Technical Product Management', 340),
  ('Director of Product Management Analytics', 350),
  ('Director of Strategic Programs', 360),
  ('EVP Finance and Corporate Development', 370),
  ('EVP, Operations', 380),
  ('Events Manager', 390),
  ('Financial Analyst', 400),
  ('Front Office Coordinator/Executive Assistant', 410),
  ('Front-End Engineer', 420),
  ('General Manager International', 430),
  ('Human Resources Business Partner', 440),
  ('Intern', 450),
  ('Internal Learning & Development Manager', 460),
  ('International Marketing Coordinator', 470),
  ('International Marketing Manager', 480),
  ('Junior AI Automation Engineer', 490),
  ('Junior Contracts Administrator', 500),
  ('Junior QA Engineer', 510),
  ('Junior Site Reliability Engineer', 520),
  ('Junior Software Engineer', 530),
  ('Lead QA Automation Engineer', 540),
  ('Lead QA Engineer', 550),
  ('Lead Senior Software Engineer', 560),
  ('Lead Site Reliability Engineer', 570),
  ('Lead Software Engineer', 580),
  ('Lead Student Safety Specialist', 590),
  ('Lead Technical Support Specialist', 600),
  ('Machine Learning Engineer', 610),
  ('Manager Finance', 620),
  ('Manager Product Design', 630),
  ('Manager, Contracts', 640),
  ('Manager, Strategic Solutions Engineering', 650),
  ('Marketing Coordinator', 660),
  ('Marketing Manager', 670),
  ('Orders and Accounts Receivables Specialist', 680),
  ('President & CFO', 690),
  ('Principal Application Security Engineer', 700),
  ('Principal Technical Product Manager', 710),
  ('Product Marketing Manager', 720),
  ('QA Automation Engineer', 730),
  ('QA Engineer', 740),
  ('Renewals Specialist', 750),
  ('Salesforce Product Manager', 760),
  ('Senior AI Automation Engineer', 770),
  ('Senior Accountant', 780),
  ('Senior Accounting Manager', 790),
  ('Senior Customer Operations Manager', 800),
  ('Senior Data Engineer', 810),
  ('Senior Director Customer Operations', 820),
  ('Senior Director Engineering', 830),
  ('Senior Director MIS', 840),
  ('Senior Director Product Management', 850),
  ('Senior Director Revenue Operations', 860),
  ('Senior Director Solutions Engineering & Support', 870),
  ('Senior Director Strategic Programs', 880),
  ('Senior Engineering Manager', 890),
  ('Senior Front-End Engineer', 900),
  ('Senior Manager Customer Experience', 910),
  ('Senior Manager, Solutions Engineering', 920),
  ('Senior Product Marketing Manager', 930),
  ('Senior QA Automation Engineer', 940),
  ('Senior QA Engineer', 950),
  ('Senior Software Engineer', 960),
  ('Senior Staff Software Engineer', 970),
  ('Senior Strategic Account Executive', 980),
  ('Senior Strategic Solutions Engineer', 990),
  ('Senior Student Safety Specialist', 1000),
  ('Senior Systems Administrator', 1010),
  ('Senior Technical Escalation Engineer', 1020),
  ('Senior Technical Support Specialist', 1030),
  ('Site Reliability Engineer', 1040),
  ('Software Engineer', 1050),
  ('Solutions Architect', 1060),
  ('Solutions Engineer', 1070),
  ('Staff Frontend Engineer', 1080),
  ('Staff Software Engineer', 1090),
  ('Strategic Account Executive', 1100),
  ('Strategic Account Manager', 1110),
  ('Strategic Solutions Engineer', 1120),
  ('Student Safety Manager', 1130),
  ('Student Safety Specialist', 1140),
  ('Systems Administrator', 1150),
  ('Team Lead Technical Support', 1160),
  ('Team Lead, Revenue Operations', 1170),
  ('Technical Escalation Engineer', 1180),
  ('Technical Product Manager', 1190),
  ('Technical Support Manager', 1200),
  ('Technical Support Specialist', 1210),
  ('Training & Enablement Manager', 1220),
  ('VP Corporate Controller', 1230),
  ('VP Engineering', 1240),
  ('VP Product Delivery', 1250),
  ('VP Sales', 1260),
  ('VP, Product IT Solutions', 1270),
  ('VP, Product Student Success', 1280)
ON CONFLICT ("title") DO NOTHING;
--> statement-breakpoint

-- 4) Link each person to their department.
UPDATE users u SET department_id = d.id, updated_at = now()
FROM (VALUES
  ('spencer.smith@lightspeedsystems.com', 'Sales'),
  ('andrew.fowler@lightspeedsystems.com', 'Sales'),
  ('kiah.long@lightspeedsystems.com', 'Sales'),
  ('harry.saunders@lightspeedsystems.com', 'Sales'),
  ('shaun.phillips@lightspeedsystems.com', 'Sales'),
  ('christopher.dunn@lightspeedsystems.com', 'Sales'),
  ('jake.de.la.garrigue@lightspeedsystems.com', 'Sales'),
  ('nicole.greig@lightspeedsystems.com', 'Sales'),
  ('alexander.woods@lightspeedsystems.com', 'Product Management'),
  ('tu.ngo@lightspeedsystems.com', 'Customer Service'),
  ('syed.muhammad.hassaan.gillani@lightspeedsystems.com', 'Customer Service'),
  ('alexander.szabo@lightspeedsystems.com', 'Product Management'),
  ('jared.varner@lightspeedsystems.com', 'Product Management'),
  ('kyle.olson@lightspeedsystems.com', 'Marketing'),
  ('brian.thomas@lightspeedsystems.com', 'Administration'),
  ('donal.mcmahon@lightspeedsystems.com', 'Administration'),
  ('amy.bennett@lightspeedsystems.com', 'Marketing'),
  ('christopher.travis@lightspeedsystems.com', 'Sales'),
  ('robert.mcmillan@lightspeedsystems.com', 'Product Development'),
  ('john.genter@lightspeedsystems.com', 'Product Development'),
  ('chase.masiel@lightspeedsystems.com', 'Content Categorization'),
  ('hailey.thomas@lightspeedsystems.com', 'Content Categorization'),
  ('alyssa.ann.silva@lightspeedsystems.com', 'Customer Service'),
  ('jeffrey.smith@lightspeedsystems.com', 'QAT'),
  ('saul.trejo@lightspeedsystems.com', 'Customer Service'),
  ('katy.shawcross@lightspeedsystems.com', 'Customer Service'),
  ('brian.truong@lightspeedsystems.com', 'Data Science'),
  ('amanda.gorena@lightspeedsystems.com', 'Marketing'),
  ('heather.james@lightspeedsystems.com', 'Human Resource'),
  ('tania.mackie.mrs@lightspeedsystems.com', 'Sales'),
  ('caitlin.mcdermott@lightspeedsystems.com', 'Product Management'),
  ('zachary.horn@lightspeedsystems.com', 'Administration'),
  ('kenneth.chitwood@lightspeedsystems.com', 'Product Development'),
  ('derek.laurie@lightspeedsystems.com', 'Product Management'),
  ('madelyne.stewart@lightspeedsystems.com', 'Marketing'),
  ('kevin.chiang@lightspeedsystems.com', 'Administration'),
  ('kevin.lawrence@lightspeedsystems.com', 'Administration'),
  ('james.laprocido@lightspeedsystems.com', 'Finance'),
  ('jake.bowman@lightspeedsystems.com', 'Finance'),
  ('katherine.williamson@lightspeedsystems.com', 'Administration'),
  ('wengel.huluka@lightspeedsystems.com', 'Product Development'),
  ('colin.mccabe@lightspeedsystems.com', 'Sales'),
  ('morgan.canales@lightspeedsystems.com', 'Human Resource'),
  ('paul.chapa@lightspeedsystems.com', 'Human Resource'),
  ('hadley.james@lightspeedsystems.com', 'Human Resource'),
  ('thayer.kacher@lightspeedsystems.com', 'Human Resource'),
  ('ava.friloux@lightspeedsystems.com', 'Human Resource'),
  ('olivia.gibbons@lightspeedsystems.com', 'Human Resource'),
  ('emma.stewart@lightspeedsystems.com', 'Human Resource'),
  ('bryan.steele@lightspeedsystems.com', 'Human Resource'),
  ('lillian.fox@lightspeedsystems.com', 'Human Resource'),
  ('winter.rhoden@lightspeedsystems.com', 'Human Resource'),
  ('dhillon.reddy@lightspeedsystems.com', 'Human Resource'),
  ('braedon.mulder@lightspeedsystems.com', 'Human Resource'),
  ('benjamin.thomas@lightspeedsystems.com', 'Human Resource'),
  ('jade.friedman@lightspeedsystems.com', 'Human Resource'),
  ('brooke.friedman@lightspeedsystems.com', 'Human Resource'),
  ('jonathan.adkins@lightspeedsystems.com', 'Administration'),
  ('megan.black@lightspeedsystems.com', 'Marketing'),
  ('liam.roberts@lightspeedsystems.com', 'Marketing'),
  ('ryan.passanisi@lightspeedsystems.com', 'Administration'),
  ('sabrina.drouin@lightspeedsystems.com', 'Administration'),
  ('kyle.escobar@lightspeedsystems.com', 'QAT'),
  ('joseph.decarlo@lightspeedsystems.com', 'Security and Hosting'),
  ('matthew.ames@lightspeedsystems.com', 'Product Development'),
  ('trung.pham@lightspeedsystems.com', 'QAT'),
  ('michelle.vargas@lightspeedsystems.com', 'QAT'),
  ('van.mualcin@lightspeedsystems.com', 'Product Development'),
  ('aiyana.mathew@lightspeedsystems.com', 'Product Development'),
  ('christopher.newkirk@lightspeedsystems.com', 'Security and Hosting'),
  ('robert.bruce@lightspeedsystems.com', 'Product Development'),
  ('preston.matheson@lightspeedsystems.com', 'Product Development'),
  ('perry.sittser@lightspeedsystems.com', 'Product Development'),
  ('carl.ahlstrand@lightspeedsystems.com', 'Product Development'),
  ('justin.woolverton@lightspeedsystems.com', 'Product Development'),
  ('jason.veselka@lightspeedsystems.com', 'Student Safety'),
  ('tichiere.womble@lightspeedsystems.com', 'Student Safety'),
  ('abraham.ybarra@lightspeedsystems.com', 'Customer Service'),
  ('dylan.claiborne@lightspeedsystems.com', 'Customer Service'),
  ('alexander.doria@lightspeedsystems.com', 'Data Science'),
  ('michael.waszazak@lightspeedsystems.com', 'Product Management'),
  ('juliana.morris@lightspeedsystems.com', 'Administration'),
  ('scott.dunham@lightspeedsystems.com', 'Finance'),
  ('bradley.rowe@lightspeedsystems.com', 'Sales Engineers'),
  ('richard.chown@lightspeedsystems.com', 'Sales Engineers'),
  ('charles.bryant@lightspeedsystems.com', 'Sales Engineers'),
  ('william.long@lightspeedsystems.com', 'Sales Engineers'),
  ('grace.mellette@lightspeedsystems.com', 'Marketing'),
  ('marcos.suarez@lightspeedsystems.com', 'Marketing'),
  ('douglas.dietert@lightspeedsystems.com', 'Finance'),
  ('kirk.orgeldinger@lightspeedsystems.com', 'Administration'),
  ('bradley.white@lightspeedsystems.com', 'Security and Compliance'),
  ('rebecca.gould@lightspeedsystems.com', 'Product Management'),
  ('jiana.khazma@lightspeedsystems.com', 'Product Marketing'),
  ('charushila.awhad@lightspeedsystems.com', 'QAT'),
  ('madhuri.balasubramanya@lightspeedsystems.com', 'QAT'),
  ('nicholas.chambers@lightspeedsystems.com', 'QAT'),
  ('brandon.jones@lightspeedsystems.com', 'QAT'),
  ('brooke.brown@lightspeedsystems.com', 'Sales'),
  ('nicole.tribo@lightspeedsystems.com', 'Sales'),
  ('adrian.rios.alvarez@lightspeedsystems.com', 'MIS'),
  ('megan.duhon@lightspeedsystems.com', 'Finance'),
  ('adrienne.synos@lightspeedsystems.com', 'Finance'),
  ('steven.miller.junior@lightspeedsystems.com', 'Administration'),
  ('alyssa.russo@lightspeedsystems.com', 'Sales Operations'),
  ('niels.dhollanderbarclay@lightspeedsystems.com', 'Data Science'),
  ('teresa.reuter@lightspeedsystems.com', 'Administration'),
  ('gerard.jr.dantel@lightspeedsystems.com', 'Product Development'),
  ('patrick.chapa@lightspeedsystems.com', 'MIS'),
  ('gregory.artzt@lightspeedsystems.com', 'Product Management'),
  ('rachel.thompson@lightspeedsystems.com', 'Sales Operations'),
  ('robert.mccartney@lightspeedsystems.com', 'Customer Service'),
  ('brock.anderson@lightspeedsystems.com', 'Administration'),
  ('bryan.anderson@lightspeedsystems.com', 'Product Development'),
  ('brock.meadors@lightspeedsystems.com', 'Product Development'),
  ('kevin.lasher@lightspeedsystems.com', 'Product Development'),
  ('casey.hann@lightspeedsystems.com', 'Sales'),
  ('wesley.cunningham@lightspeedsystems.com', 'Sales Engineers'),
  ('larissa.negreiros.somaio@lightspeedsystems.com', 'Product Marketing'),
  ('gijo.johny@lightspeedsystems.com', 'QAT'),
  ('jenisha.karmacharya@lightspeedsystems.com', 'QAT'),
  ('andrew.cribari@lightspeedsystems.com', 'QAT'),
  ('jeffrey.zwick@lightspeedsystems.com', 'QAT'),
  ('steven.landwehr@lightspeedsystems.com', 'Product Development'),
  ('neil.shaw@lightspeedsystems.com', 'Product Development'),
  ('nathan.johnson@lightspeedsystems.com', 'Product Development'),
  ('scott.meeks@lightspeedsystems.com', 'Sales'),
  ('shad.mcgaha@lightspeedsystems.com', 'Sales Engineers'),
  ('whitney.veatch@lightspeedsystems.com', 'Student Safety'),
  ('sinead.williams@lightspeedsystems.com', 'Student Safety'),
  ('zakkiyya.purnell@lightspeedsystems.com', 'Student Safety'),
  ('kurstye.tillmon@lightspeedsystems.com', 'Student Safety'),
  ('nykayla.carter@lightspeedsystems.com', 'Student Safety'),
  ('angela.mazza@lightspeedsystems.com', 'Student Safety'),
  ('alexander.hesse@lightspeedsystems.com', 'MIS'),
  ('ryan.stufflebeam@lightspeedsystems.com', 'Customer Success Engineering'),
  ('wing.mar@lightspeedsystems.com', 'Customer Service'),
  ('esteban.diocares@lightspeedsystems.com', 'Security and Hosting'),
  ('ryan.oglesby@lightspeedsystems.com', 'Security and Hosting'),
  ('anita.krueger@lightspeedsystems.com', 'Security and Hosting'),
  ('eric.cruz@lightspeedsystems.com', 'Product Development'),
  ('jack.mcdonnell@lightspeedsystems.com', 'Product Development'),
  ('christian.trahan@lightspeedsystems.com', 'Product Development'),
  ('andrew.hecht@lightspeedsystems.com', 'Product Development'),
  ('christina.atkinson@lightspeedsystems.com', 'Customer Success Engineering'),
  ('quinten.oldaker@lightspeedsystems.com', 'Customer Success Engineering'),
  ('ramy.sahouri@lightspeedsystems.com', 'Customer Success Engineering'),
  ('joel.walmsley@lightspeedsystems.com', 'Customer Success Engineering'),
  ('dante.munoz@lightspeedsystems.com', 'Customer Success Engineering'),
  ('alex.wade@lightspeedsystems.com', 'Product Development'),
  ('jason.isaac@lightspeedsystems.com', 'Product Development'),
  ('mitchell.laurrenring@lightspeedsystems.com', 'Product Development'),
  ('keaton.smith@lightspeedsystems.com', 'Sales'),
  ('sergio.villegas@lightspeedsystems.com', 'Sales'),
  ('nicholas.zema@lightspeedsystems.com', 'Sales'),
  ('christopher.spink@lightspeedsystems.com', 'Sales'),
  ('sam.howard.mr@lightspeedsystems.com', 'Sales'),
  ('jaeden.richards@lightspeedsystems.com', 'Sales'),
  ('erika.johnson@lightspeedsystems.com', 'Sales'),
  ('alecia.boggess@lightspeedsystems.com', 'Sales'),
  ('ann.marie.martinez@lightspeedsystems.com', 'Sales'),
  ('michael.roddey@lightspeedsystems.com', 'Sales'),
  ('lauren.mcnair@lightspeedsystems.com', 'Sales'),
  ('casey.butera@lightspeedsystems.com', 'Sales'),
  ('ross.mcaden@lightspeedsystems.com', 'Sales'),
  ('trevor.davis@lightspeedsystems.com', 'Sales Engineers'),
  ('alexander.sands@lightspeedsystems.com', 'Sales Engineers'),
  ('matthew.nelson@lightspeedsystems.com', 'Sales Engineers'),
  ('austin.sweet@lightspeedsystems.com', 'Sales Engineers'),
  ('colin.fulton@lightspeedsystems.com', 'Sales Engineers'),
  ('robert.hancock@lightspeedsystems.com', 'Sales Engineers'),
  ('daniel.dunn@lightspeedsystems.com', 'Sales Engineers'),
  ('alexander.crouse@lightspeedsystems.com', 'Sales Engineers'),
  ('december.wilks@lightspeedsystems.com', 'Student Safety'),
  ('tracy.craig@lightspeedsystems.com', 'Student Safety'),
  ('ricky.salter@lightspeedsystems.com', 'Student Safety'),
  ('jolie.boodansingh@lightspeedsystems.com', 'Student Safety'),
  ('colleen.clark@lightspeedsystems.com', 'Student Safety'),
  ('lydell.craig@lightspeedsystems.com', 'Student Safety'),
  ('cristal.cuellar@lightspeedsystems.com', 'Student Safety'),
  ('nathan.davila@lightspeedsystems.com', 'Student Safety'),
  ('jerry.flores@lightspeedsystems.com', 'Student Safety'),
  ('shanna.johnson@lightspeedsystems.com', 'Student Safety'),
  ('christina.mares@lightspeedsystems.com', 'Student Safety'),
  ('jason.montes@lightspeedsystems.com', 'Student Safety'),
  ('katelin.revels@lightspeedsystems.com', 'Student Safety'),
  ('shakira.romero@lightspeedsystems.com', 'Student Safety'),
  ('danielle.rubio@lightspeedsystems.com', 'Student Safety'),
  ('armahn.turk@lightspeedsystems.com', 'Student Safety'),
  ('marlisa.mungo@lightspeedsystems.com', 'Student Safety'),
  ('tameka.smith@lightspeedsystems.com', 'Student Safety'),
  ('danielle.adams@lightspeedsystems.com', 'Student Safety'),
  ('rashida.brown@lightspeedsystems.com', 'Student Safety'),
  ('albert.garcia@lightspeedsystems.com', 'Student Safety'),
  ('kian.curran@lightspeedsystems.com', 'Student Safety'),
  ('nathan.estrada@lightspeedsystems.com', 'Student Safety'),
  ('william.hellemsmoody@lightspeedsystems.com', 'MIS'),
  ('andy.bennetta@lightspeedsystems.com', 'Customer Service'),
  ('luke.shearin@lightspeedsystems.com', 'Sales Operations'),
  ('cameron.meyer@lightspeedsystems.com', 'Customer Service'),
  ('enrique.michel@lightspeedsystems.com', 'Customer Service'),
  ('chasity.lyson@lightspeedsystems.com', 'Customer Service'),
  ('michelle.mcgovern@lightspeedsystems.com', 'Scrum'),
  ('vernie.ogden@lightspeedsystems.com', 'Scrum'),
  ('leigh.morris@lightspeedsystems.com', 'QAT'),
  ('travis.bullock@lightspeedsystems.com', 'Customer Service'),
  ('juan.rodriguez.maldonado@lightspeedsystems.com', 'Customer Service'),
  ('frank.romero@lightspeedsystems.com', 'Customer Service'),
  ('marie.wittry@lightspeedsystems.com', 'Customer Service'),
  ('lewis.brown@lightspeedsystems.com', 'Customer Service'),
  ('jide.oke@lightspeedsystems.com', 'Customer Service'),
  ('khaled.uddin@lightspeedsystems.com', 'Customer Service'),
  ('krista.delk@lightspeedsystems.com', 'Customer Success'),
  ('cindy.moore@lightspeedsystems.com', 'Customer Success'),
  ('samantha.revels@lightspeedsystems.com', 'Customer Success'),
  ('gregory.funk@lightspeedsystems.com', 'Finance'),
  ('ryan.bond@lightspeedsystems.com', 'Product Development'),
  ('jai.pandu@lightspeedsystems.com', 'Product Development'),
  ('jared.accardo@lightspeedsystems.com', 'QAT'),
  ('kevin.askew@lightspeedsystems.com', 'Sales'),
  ('michael.boggess@lightspeedsystems.com', 'Sales'),
  ('michael.durando@lightspeedsystems.com', 'Sales'),
  ('matthew.burg@lightspeedsystems.com', 'Product Management'),
  ('jennifer.duer@lightspeedsystems.com', 'Product Management')
) AS m(email, dept)
JOIN departments d ON d.name = m.dept
WHERE u.email = m.email;
--> statement-breakpoint

-- 5) Link each person to their job title.
UPDATE users u SET job_title_id = jt.id, updated_at = now()
FROM (VALUES
  ('spencer.smith@lightspeedsystems.com', 'Account Executive'),
  ('andrew.fowler@lightspeedsystems.com', 'Account Executive'),
  ('kiah.long@lightspeedsystems.com', 'Account Manager'),
  ('harry.saunders@lightspeedsystems.com', 'Account Manager'),
  ('shaun.phillips@lightspeedsystems.com', 'Acting Director of Sales EMEIA'),
  ('christopher.dunn@lightspeedsystems.com', 'Associate Account Executive'),
  ('jake.de.la.garrigue@lightspeedsystems.com', 'Associate Account Executive'),
  ('nicole.greig@lightspeedsystems.com', 'Associate Account Manager'),
  ('alexander.woods@lightspeedsystems.com', 'Associate Technical Product Manager'),
  ('tu.ngo@lightspeedsystems.com', 'Associate Technical Support Specialist'),
  ('syed.muhammad.hassaan.gillani@lightspeedsystems.com', 'Associate Technical Support Specialist'),
  ('alexander.szabo@lightspeedsystems.com', 'Business Analyst'),
  ('jared.varner@lightspeedsystems.com', 'Business Analyst'),
  ('kyle.olson@lightspeedsystems.com', 'Business Development Representative'),
  ('brian.thomas@lightspeedsystems.com', 'CEO & Founder'),
  ('donal.mcmahon@lightspeedsystems.com', 'Chief AI Officer'),
  ('amy.bennett@lightspeedsystems.com', 'Chief of Staff'),
  ('christopher.travis@lightspeedsystems.com', 'Chief Revenue Officer'),
  ('robert.mcmillan@lightspeedsystems.com', 'Chief Technology Officer'),
  ('john.genter@lightspeedsystems.com', 'CISO'),
  ('chase.masiel@lightspeedsystems.com', 'Content Categorization Specialist'),
  ('hailey.thomas@lightspeedsystems.com', 'Content Categorization Specialist'),
  ('alyssa.ann.silva@lightspeedsystems.com', 'Customer Operations Analyst'),
  ('jeffrey.smith@lightspeedsystems.com', 'Customer Quality Manager'),
  ('saul.trejo@lightspeedsystems.com', 'Customer Service Representative'),
  ('katy.shawcross@lightspeedsystems.com', 'Customer Service Representative'),
  ('brian.truong@lightspeedsystems.com', 'Data Platform Manager'),
  ('amanda.gorena@lightspeedsystems.com', 'Director Corporate Marketing'),
  ('heather.james@lightspeedsystems.com', 'Director Human Resources'),
  ('tania.mackie.mrs@lightspeedsystems.com', 'Director International Safeguarding & Digital Transformation'),
  ('caitlin.mcdermott@lightspeedsystems.com', 'Director of Product Management Analytics'),
  ('zachary.horn@lightspeedsystems.com', 'Director of Strategic Programs'),
  ('kenneth.chitwood@lightspeedsystems.com', 'Director Site Reliability'),
  ('derek.laurie@lightspeedsystems.com', 'Director Technical Product Management'),
  ('madelyne.stewart@lightspeedsystems.com', 'Events Manager'),
  ('kevin.chiang@lightspeedsystems.com', 'EVP Finance and Corporate Development'),
  ('kevin.lawrence@lightspeedsystems.com', 'EVP, Operations'),
  ('james.laprocido@lightspeedsystems.com', 'Financial Analyst'),
  ('jake.bowman@lightspeedsystems.com', 'Financial Analyst'),
  ('katherine.williamson@lightspeedsystems.com', 'Front Office Coordinator/Executive Assistant'),
  ('wengel.huluka@lightspeedsystems.com', 'Front-End Engineer'),
  ('colin.mccabe@lightspeedsystems.com', 'General Manager International'),
  ('morgan.canales@lightspeedsystems.com', 'Human Resources Business Partner'),
  ('paul.chapa@lightspeedsystems.com', 'Intern'),
  ('hadley.james@lightspeedsystems.com', 'Intern'),
  ('thayer.kacher@lightspeedsystems.com', 'Intern'),
  ('ava.friloux@lightspeedsystems.com', 'Intern'),
  ('olivia.gibbons@lightspeedsystems.com', 'Intern'),
  ('emma.stewart@lightspeedsystems.com', 'Intern'),
  ('bryan.steele@lightspeedsystems.com', 'Intern'),
  ('lillian.fox@lightspeedsystems.com', 'Intern'),
  ('winter.rhoden@lightspeedsystems.com', 'Intern'),
  ('dhillon.reddy@lightspeedsystems.com', 'Intern'),
  ('braedon.mulder@lightspeedsystems.com', 'Intern'),
  ('benjamin.thomas@lightspeedsystems.com', 'Intern'),
  ('jade.friedman@lightspeedsystems.com', 'Intern'),
  ('brooke.friedman@lightspeedsystems.com', 'Intern'),
  ('jonathan.adkins@lightspeedsystems.com', 'Internal Learning & Development Manager'),
  ('megan.black@lightspeedsystems.com', 'International Marketing Coordinator'),
  ('liam.roberts@lightspeedsystems.com', 'International Marketing Manager'),
  ('ryan.passanisi@lightspeedsystems.com', 'Junior AI Automation Engineer'),
  ('sabrina.drouin@lightspeedsystems.com', 'Junior Contracts Administrator'),
  ('kyle.escobar@lightspeedsystems.com', 'Junior QA Engineer'),
  ('joseph.decarlo@lightspeedsystems.com', 'Junior Site Reliability Engineer'),
  ('matthew.ames@lightspeedsystems.com', 'Junior Software Engineer'),
  ('trung.pham@lightspeedsystems.com', 'Lead QA Automation Engineer'),
  ('michelle.vargas@lightspeedsystems.com', 'Lead QA Engineer'),
  ('van.mualcin@lightspeedsystems.com', 'Lead Senior Software Engineer'),
  ('aiyana.mathew@lightspeedsystems.com', 'Lead Senior Software Engineer'),
  ('christopher.newkirk@lightspeedsystems.com', 'Lead Site Reliability Engineer'),
  ('robert.bruce@lightspeedsystems.com', 'Lead Software Engineer'),
  ('preston.matheson@lightspeedsystems.com', 'Lead Software Engineer'),
  ('perry.sittser@lightspeedsystems.com', 'Lead Software Engineer'),
  ('carl.ahlstrand@lightspeedsystems.com', 'Lead Software Engineer'),
  ('justin.woolverton@lightspeedsystems.com', 'Lead Software Engineer'),
  ('jason.veselka@lightspeedsystems.com', 'Lead Student Safety Specialist'),
  ('tichiere.womble@lightspeedsystems.com', 'Lead Student Safety Specialist'),
  ('abraham.ybarra@lightspeedsystems.com', 'Lead Technical Support Specialist'),
  ('dylan.claiborne@lightspeedsystems.com', 'Lead Technical Support Specialist'),
  ('alexander.doria@lightspeedsystems.com', 'Machine Learning Engineer'),
  ('michael.waszazak@lightspeedsystems.com', 'Manager Product Design'),
  ('juliana.morris@lightspeedsystems.com', 'Manager, Contracts'),
  ('scott.dunham@lightspeedsystems.com', 'Manager Finance'),
  ('bradley.rowe@lightspeedsystems.com', 'Manager, Strategic Solutions Engineering'),
  ('richard.chown@lightspeedsystems.com', 'Manager, Strategic Solutions Engineering'),
  ('charles.bryant@lightspeedsystems.com', 'Manager, Strategic Solutions Engineering'),
  ('william.long@lightspeedsystems.com', 'Manager, Strategic Solutions Engineering'),
  ('grace.mellette@lightspeedsystems.com', 'Marketing Coordinator'),
  ('marcos.suarez@lightspeedsystems.com', 'Marketing Manager'),
  ('douglas.dietert@lightspeedsystems.com', 'Orders and Accounts Receivables Specialist'),
  ('kirk.orgeldinger@lightspeedsystems.com', 'President & CFO'),
  ('bradley.white@lightspeedsystems.com', 'Principal Application Security Engineer'),
  ('rebecca.gould@lightspeedsystems.com', 'Principal Technical Product Manager'),
  ('jiana.khazma@lightspeedsystems.com', 'Product Marketing Manager'),
  ('charushila.awhad@lightspeedsystems.com', 'QA Automation Engineer'),
  ('madhuri.balasubramanya@lightspeedsystems.com', 'QA Engineer'),
  ('nicholas.chambers@lightspeedsystems.com', 'QA Engineer'),
  ('brandon.jones@lightspeedsystems.com', 'QA Engineer'),
  ('brooke.brown@lightspeedsystems.com', 'Renewals Specialist'),
  ('nicole.tribo@lightspeedsystems.com', 'Renewals Specialist'),
  ('adrian.rios.alvarez@lightspeedsystems.com', 'Salesforce Product Manager'),
  ('megan.duhon@lightspeedsystems.com', 'Senior Accountant'),
  ('adrienne.synos@lightspeedsystems.com', 'Senior Accounting Manager'),
  ('steven.miller.junior@lightspeedsystems.com', 'Senior AI Automation Engineer'),
  ('alyssa.russo@lightspeedsystems.com', 'Senior Customer Operations Manager'),
  ('niels.dhollanderbarclay@lightspeedsystems.com', 'Senior Data Engineer'),
  ('teresa.reuter@lightspeedsystems.com', 'Senior Director Customer Operations'),
  ('gerard.jr.dantel@lightspeedsystems.com', 'Senior Director Engineering'),
  ('patrick.chapa@lightspeedsystems.com', 'Senior Director MIS'),
  ('gregory.artzt@lightspeedsystems.com', 'Senior Director Product Management'),
  ('rachel.thompson@lightspeedsystems.com', 'Senior Director Revenue Operations'),
  ('robert.mccartney@lightspeedsystems.com', 'Senior Director Solutions Engineering & Support'),
  ('brock.anderson@lightspeedsystems.com', 'Senior Director Strategic Programs'),
  ('bryan.anderson@lightspeedsystems.com', 'Senior Engineering Manager'),
  ('brock.meadors@lightspeedsystems.com', 'Senior Engineering Manager'),
  ('kevin.lasher@lightspeedsystems.com', 'Senior Front-End Engineer'),
  ('casey.hann@lightspeedsystems.com', 'Senior Manager Customer Experience'),
  ('wesley.cunningham@lightspeedsystems.com', 'Senior Manager, Solutions Engineering'),
  ('larissa.negreiros.somaio@lightspeedsystems.com', 'Senior Product Marketing Manager'),
  ('gijo.johny@lightspeedsystems.com', 'Senior QA Automation Engineer'),
  ('jenisha.karmacharya@lightspeedsystems.com', 'Senior QA Automation Engineer'),
  ('andrew.cribari@lightspeedsystems.com', 'Senior QA Engineer'),
  ('jeffrey.zwick@lightspeedsystems.com', 'Senior QA Engineer'),
  ('steven.landwehr@lightspeedsystems.com', 'Senior Software Engineer'),
  ('neil.shaw@lightspeedsystems.com', 'Senior Software Engineer'),
  ('nathan.johnson@lightspeedsystems.com', 'Senior Staff Software Engineer'),
  ('scott.meeks@lightspeedsystems.com', 'Senior Strategic Account Executive'),
  ('shad.mcgaha@lightspeedsystems.com', 'Senior Strategic Solutions Engineer'),
  ('whitney.veatch@lightspeedsystems.com', 'Senior Student Safety Specialist'),
  ('sinead.williams@lightspeedsystems.com', 'Senior Student Safety Specialist'),
  ('zakkiyya.purnell@lightspeedsystems.com', 'Senior Student Safety Specialist'),
  ('kurstye.tillmon@lightspeedsystems.com', 'Senior Student Safety Specialist'),
  ('nykayla.carter@lightspeedsystems.com', 'Senior Student Safety Specialist'),
  ('angela.mazza@lightspeedsystems.com', 'Senior Student Safety Specialist'),
  ('alexander.hesse@lightspeedsystems.com', 'Senior Systems Administrator'),
  ('ryan.stufflebeam@lightspeedsystems.com', 'Senior Technical Escalation Engineer'),
  ('wing.mar@lightspeedsystems.com', 'Senior Technical Support Specialist'),
  ('esteban.diocares@lightspeedsystems.com', 'Site Reliability Engineer'),
  ('ryan.oglesby@lightspeedsystems.com', 'Site Reliability Engineer'),
  ('anita.krueger@lightspeedsystems.com', 'Site Reliability Engineer'),
  ('eric.cruz@lightspeedsystems.com', 'Software Engineer'),
  ('jack.mcdonnell@lightspeedsystems.com', 'Software Engineer'),
  ('christian.trahan@lightspeedsystems.com', 'Software Engineer'),
  ('andrew.hecht@lightspeedsystems.com', 'Solutions Architect'),
  ('christina.atkinson@lightspeedsystems.com', 'Solutions Engineer'),
  ('quinten.oldaker@lightspeedsystems.com', 'Solutions Engineer'),
  ('ramy.sahouri@lightspeedsystems.com', 'Solutions Engineer'),
  ('joel.walmsley@lightspeedsystems.com', 'Solutions Engineer'),
  ('dante.munoz@lightspeedsystems.com', 'Solutions Engineer'),
  ('alex.wade@lightspeedsystems.com', 'Staff Frontend Engineer'),
  ('jason.isaac@lightspeedsystems.com', 'Staff Software Engineer'),
  ('mitchell.laurrenring@lightspeedsystems.com', 'Staff Software Engineer'),
  ('keaton.smith@lightspeedsystems.com', 'Strategic Account Executive'),
  ('sergio.villegas@lightspeedsystems.com', 'Strategic Account Executive'),
  ('nicholas.zema@lightspeedsystems.com', 'Strategic Account Executive'),
  ('christopher.spink@lightspeedsystems.com', 'Strategic Account Executive'),
  ('sam.howard.mr@lightspeedsystems.com', 'Strategic Account Executive'),
  ('jaeden.richards@lightspeedsystems.com', 'Strategic Account Executive'),
  ('erika.johnson@lightspeedsystems.com', 'Strategic Account Manager'),
  ('alecia.boggess@lightspeedsystems.com', 'Strategic Account Manager'),
  ('ann.marie.martinez@lightspeedsystems.com', 'Strategic Account Manager'),
  ('michael.roddey@lightspeedsystems.com', 'Strategic Account Manager'),
  ('lauren.mcnair@lightspeedsystems.com', 'Strategic Account Manager'),
  ('casey.butera@lightspeedsystems.com', 'Strategic Account Manager'),
  ('ross.mcaden@lightspeedsystems.com', 'Strategic Account Manager'),
  ('trevor.davis@lightspeedsystems.com', 'Strategic Solutions Engineer'),
  ('alexander.sands@lightspeedsystems.com', 'Strategic Solutions Engineer'),
  ('matthew.nelson@lightspeedsystems.com', 'Strategic Solutions Engineer'),
  ('austin.sweet@lightspeedsystems.com', 'Strategic Solutions Engineer'),
  ('colin.fulton@lightspeedsystems.com', 'Strategic Solutions Engineer'),
  ('robert.hancock@lightspeedsystems.com', 'Strategic Solutions Engineer'),
  ('daniel.dunn@lightspeedsystems.com', 'Strategic Solutions Engineer'),
  ('alexander.crouse@lightspeedsystems.com', 'Strategic Solutions Engineer'),
  ('december.wilks@lightspeedsystems.com', 'Student Safety Manager'),
  ('tracy.craig@lightspeedsystems.com', 'Student Safety Manager'),
  ('ricky.salter@lightspeedsystems.com', 'Student Safety Manager'),
  ('jolie.boodansingh@lightspeedsystems.com', 'Student Safety Specialist'),
  ('colleen.clark@lightspeedsystems.com', 'Student Safety Specialist'),
  ('lydell.craig@lightspeedsystems.com', 'Student Safety Specialist'),
  ('cristal.cuellar@lightspeedsystems.com', 'Student Safety Specialist'),
  ('nathan.davila@lightspeedsystems.com', 'Student Safety Specialist'),
  ('jerry.flores@lightspeedsystems.com', 'Student Safety Specialist'),
  ('shanna.johnson@lightspeedsystems.com', 'Student Safety Specialist'),
  ('christina.mares@lightspeedsystems.com', 'Student Safety Specialist'),
  ('jason.montes@lightspeedsystems.com', 'Student Safety Specialist'),
  ('katelin.revels@lightspeedsystems.com', 'Student Safety Specialist'),
  ('shakira.romero@lightspeedsystems.com', 'Student Safety Specialist'),
  ('danielle.rubio@lightspeedsystems.com', 'Student Safety Specialist'),
  ('armahn.turk@lightspeedsystems.com', 'Student Safety Specialist'),
  ('marlisa.mungo@lightspeedsystems.com', 'Student Safety Specialist'),
  ('tameka.smith@lightspeedsystems.com', 'Student Safety Specialist'),
  ('danielle.adams@lightspeedsystems.com', 'Student Safety Specialist'),
  ('rashida.brown@lightspeedsystems.com', 'Student Safety Specialist'),
  ('albert.garcia@lightspeedsystems.com', 'Student Safety Specialist'),
  ('kian.curran@lightspeedsystems.com', 'Student Safety Specialist'),
  ('nathan.estrada@lightspeedsystems.com', 'Student Safety Specialist'),
  ('william.hellemsmoody@lightspeedsystems.com', 'Systems Administrator'),
  ('andy.bennetta@lightspeedsystems.com', 'Team Lead Technical Support'),
  ('luke.shearin@lightspeedsystems.com', 'Team Lead, Revenue Operations'),
  ('cameron.meyer@lightspeedsystems.com', 'Technical Escalation Engineer'),
  ('enrique.michel@lightspeedsystems.com', 'Technical Escalation Engineer'),
  ('chasity.lyson@lightspeedsystems.com', 'Technical Escalation Engineer'),
  ('michelle.mcgovern@lightspeedsystems.com', 'Technical Product Manager'),
  ('vernie.ogden@lightspeedsystems.com', 'Technical Product Manager'),
  ('leigh.morris@lightspeedsystems.com', 'Technical Product Manager'),
  ('travis.bullock@lightspeedsystems.com', 'Technical Support Manager'),
  ('juan.rodriguez.maldonado@lightspeedsystems.com', 'Technical Support Specialist'),
  ('frank.romero@lightspeedsystems.com', 'Technical Support Specialist'),
  ('marie.wittry@lightspeedsystems.com', 'Technical Support Specialist'),
  ('lewis.brown@lightspeedsystems.com', 'Technical Support Specialist'),
  ('jide.oke@lightspeedsystems.com', 'Technical Support Specialist'),
  ('khaled.uddin@lightspeedsystems.com', 'Technical Support Specialist'),
  ('krista.delk@lightspeedsystems.com', 'Training & Enablement Manager'),
  ('cindy.moore@lightspeedsystems.com', 'Training & Enablement Manager'),
  ('samantha.revels@lightspeedsystems.com', 'Training & Enablement Manager'),
  ('gregory.funk@lightspeedsystems.com', 'VP Corporate Controller'),
  ('ryan.bond@lightspeedsystems.com', 'VP Engineering'),
  ('jai.pandu@lightspeedsystems.com', 'VP Engineering'),
  ('jared.accardo@lightspeedsystems.com', 'VP Product Delivery'),
  ('kevin.askew@lightspeedsystems.com', 'VP Sales'),
  ('michael.boggess@lightspeedsystems.com', 'VP Sales'),
  ('michael.durando@lightspeedsystems.com', 'VP Sales'),
  ('matthew.burg@lightspeedsystems.com', 'VP, Product IT Solutions'),
  ('jennifer.duer@lightspeedsystems.com', 'VP, Product Student Success')
) AS m(email, title)
JOIN job_titles jt ON jt.title = m.title
WHERE u.email = m.email;
