-- 0025 Enrich from the official 'Reporting Structure' report (Position Seat
-- Detail). Two additions the org chart did not carry: (1) each person's HR
-- employee code -> users.external_id (core data), and (2) the 11 vacant seats
-- as clearly-labeled open-req nodes in the org (title + department + manager),
-- so the reporting structure shows open headcount. Reporting lines and families
-- were verified identical to the chart, so nothing there changes.
-- Idempotent: set-based external_id backfill + ON CONFLICT(email) upsert.

-- 1) Employee codes -> external_id (matched by canonical email).
UPDATE users u SET external_id = m.code, updated_at = now()
FROM (VALUES
  ('spencer.smith@lightspeedsystems.com', 'A127'),
  ('andrew.fowler@lightspeedsystems.com', 'A144'),
  ('kiah.long@lightspeedsystems.com', 'A1DP'),
  ('harry.saunders@lightspeedsystems.com', 'A1DB'),
  ('shaun.phillips@lightspeedsystems.com', 'A1FN'),
  ('christopher.dunn@lightspeedsystems.com', 'A105'),
  ('jake.de.la.garrigue@lightspeedsystems.com', 'A0Y1'),
  ('nicole.greig@lightspeedsystems.com', 'A1BA'),
  ('alexander.woods@lightspeedsystems.com', 'A0P0'),
  ('tu.ngo@lightspeedsystems.com', 'A1FW'),
  ('syed.muhammad.hassaan.gillani@lightspeedsystems.com', 'A1BX'),
  ('alexander.szabo@lightspeedsystems.com', 'A1BZ'),
  ('jared.varner@lightspeedsystems.com', 'A0XU'),
  ('kyle.olson@lightspeedsystems.com', 'A1FT'),
  ('brian.thomas@lightspeedsystems.com', 'A0O2'),
  ('donal.mcmahon@lightspeedsystems.com', 'A120'),
  ('amy.bennett@lightspeedsystems.com', 'A0NV'),
  ('christopher.travis@lightspeedsystems.com', 'A0P8'),
  ('robert.mcmillan@lightspeedsystems.com', 'A0QN'),
  ('john.genter@lightspeedsystems.com', 'A0OT'),
  ('chase.masiel@lightspeedsystems.com', 'A0TL'),
  ('hailey.thomas@lightspeedsystems.com', 'A0XG'),
  ('alyssa.ann.silva@lightspeedsystems.com', 'A0YK'),
  ('jeffrey.smith@lightspeedsystems.com', 'A0OX'),
  ('saul.trejo@lightspeedsystems.com', 'A10C'),
  ('katy.shawcross@lightspeedsystems.com', 'A1BI'),
  ('brian.truong@lightspeedsystems.com', 'A0VH'),
  ('amanda.gorena@lightspeedsystems.com', 'A0SY'),
  ('heather.james@lightspeedsystems.com', 'A0O5'),
  ('tania.mackie.mrs@lightspeedsystems.com', 'A1B4'),
  ('caitlin.mcdermott@lightspeedsystems.com', 'A0UC'),
  ('zachary.horn@lightspeedsystems.com', 'A0XK'),
  ('kenneth.chitwood@lightspeedsystems.com', 'A0P7'),
  ('derek.laurie@lightspeedsystems.com', 'A0UN'),
  ('madelyne.stewart@lightspeedsystems.com', 'A201'),
  ('kevin.chiang@lightspeedsystems.com', 'A0SL'),
  ('kevin.lawrence@lightspeedsystems.com', 'A0X6'),
  ('james.laprocido@lightspeedsystems.com', 'A11Z'),
  ('jake.bowman@lightspeedsystems.com', 'A1BM'),
  ('katherine.williamson@lightspeedsystems.com', 'A0SJ'),
  ('wengel.huluka@lightspeedsystems.com', 'A104'),
  ('colin.mccabe@lightspeedsystems.com', 'A1D2'),
  ('morgan.canales@lightspeedsystems.com', 'A1B0'),
  ('paul.chapa@lightspeedsystems.com', 'A0XJ'),
  ('hadley.james@lightspeedsystems.com', 'A0U6'),
  ('thayer.kacher@lightspeedsystems.com', 'A1BO'),
  ('ava.friloux@lightspeedsystems.com', 'A1BP'),
  ('olivia.gibbons@lightspeedsystems.com', 'A1BQ'),
  ('emma.stewart@lightspeedsystems.com', 'A1BR'),
  ('bryan.steele@lightspeedsystems.com', 'A1AN'),
  ('lillian.fox@lightspeedsystems.com', 'A1BS'),
  ('winter.rhoden@lightspeedsystems.com', 'A1BT'),
  ('dhillon.reddy@lightspeedsystems.com', 'A1BU'),
  ('braedon.mulder@lightspeedsystems.com', 'A1AM'),
  ('benjamin.thomas@lightspeedsystems.com', 'A1BW'),
  ('jade.friedman@lightspeedsystems.com', 'A1BY'),
  ('brooke.friedman@lightspeedsystems.com', 'A1C2'),
  ('jonathan.adkins@lightspeedsystems.com', 'A122'),
  ('megan.black@lightspeedsystems.com', 'A1DY'),
  ('liam.roberts@lightspeedsystems.com', 'A1DU'),
  ('ryan.passanisi@lightspeedsystems.com', 'A1BL'),
  ('sabrina.drouin@lightspeedsystems.com', 'A1BJ'),
  ('kyle.escobar@lightspeedsystems.com', 'A0Z9'),
  ('joseph.decarlo@lightspeedsystems.com', 'A0QC'),
  ('matthew.ames@lightspeedsystems.com', 'A0UQ'),
  ('trung.pham@lightspeedsystems.com', 'A0R3'),
  ('michelle.vargas@lightspeedsystems.com', 'A0XY'),
  ('van.mualcin@lightspeedsystems.com', 'A0VW'),
  ('aiyana.mathew@lightspeedsystems.com', 'A11E'),
  ('christopher.newkirk@lightspeedsystems.com', 'A0PP'),
  ('robert.bruce@lightspeedsystems.com', 'A0RR'),
  ('preston.matheson@lightspeedsystems.com', 'A0R8'),
  ('perry.sittser@lightspeedsystems.com', 'A0UP'),
  ('carl.ahlstrand@lightspeedsystems.com', 'A0WS'),
  ('justin.woolverton@lightspeedsystems.com', 'A128'),
  ('jason.veselka@lightspeedsystems.com', 'A0U1'),
  ('tichiere.womble@lightspeedsystems.com', 'A11W'),
  ('abraham.ybarra@lightspeedsystems.com', 'A0SG'),
  ('dylan.claiborne@lightspeedsystems.com', 'A10N'),
  ('alexander.doria@lightspeedsystems.com', 'A0Z1'),
  ('michael.waszazak@lightspeedsystems.com', 'A0PU'),
  ('juliana.morris@lightspeedsystems.com', 'A110'),
  ('scott.dunham@lightspeedsystems.com', 'A0UE'),
  ('bradley.rowe@lightspeedsystems.com', 'A1AJ'),
  ('richard.chown@lightspeedsystems.com', 'A1FG'),
  ('charles.bryant@lightspeedsystems.com', 'A1C0'),
  ('william.long@lightspeedsystems.com', 'A0P5'),
  ('grace.mellette@lightspeedsystems.com', 'A10K'),
  ('marcos.suarez@lightspeedsystems.com', 'A1BB'),
  ('douglas.dietert@lightspeedsystems.com', 'A0OM'),
  ('kirk.orgeldinger@lightspeedsystems.com', 'A0NU'),
  ('bradley.white@lightspeedsystems.com', 'A0QL'),
  ('rebecca.gould@lightspeedsystems.com', 'A0SS'),
  ('jiana.khazma@lightspeedsystems.com', 'A0YH'),
  ('charushila.awhad@lightspeedsystems.com', 'A0UO'),
  ('madhuri.balasubramanya@lightspeedsystems.com', 'A0VE'),
  ('nicholas.chambers@lightspeedsystems.com', 'A0RP'),
  ('brandon.jones@lightspeedsystems.com', 'A0ON'),
  ('brooke.brown@lightspeedsystems.com', 'A10X'),
  ('nicole.tribo@lightspeedsystems.com', 'A1BN'),
  ('adrian.rios.alvarez@lightspeedsystems.com', 'A0X7'),
  ('megan.duhon@lightspeedsystems.com', 'A0ZL'),
  ('adrienne.synos@lightspeedsystems.com', 'A0V8'),
  ('steven.miller.junior@lightspeedsystems.com', 'A1B9'),
  ('alyssa.russo@lightspeedsystems.com', 'A11L'),
  ('niels.dhollanderbarclay@lightspeedsystems.com', 'A0VR'),
  ('teresa.reuter@lightspeedsystems.com', 'A112'),
  ('gerard.jr.dantel@lightspeedsystems.com', 'A115'),
  ('patrick.chapa@lightspeedsystems.com', 'A0PV'),
  ('gregory.artzt@lightspeedsystems.com', 'A117'),
  ('rachel.thompson@lightspeedsystems.com', 'A0W3'),
  ('robert.mccartney@lightspeedsystems.com', 'A0QJ'),
  ('brock.anderson@lightspeedsystems.com', 'A0Y0'),
  ('bryan.anderson@lightspeedsystems.com', 'A0PO'),
  ('brock.meadors@lightspeedsystems.com', 'A0P6'),
  ('kevin.lasher@lightspeedsystems.com', 'A0UJ'),
  ('casey.hann@lightspeedsystems.com', 'A11T'),
  ('wesley.cunningham@lightspeedsystems.com', 'A0T7'),
  ('larissa.negreiros.somaio@lightspeedsystems.com', 'A0Y9'),
  ('gijo.johny@lightspeedsystems.com', 'A0US'),
  ('jenisha.karmacharya@lightspeedsystems.com', 'A0WQ'),
  ('andrew.cribari@lightspeedsystems.com', 'A0SH'),
  ('jeffrey.zwick@lightspeedsystems.com', 'A0VK'),
  ('steven.landwehr@lightspeedsystems.com', 'A0WW'),
  ('neil.shaw@lightspeedsystems.com', 'A0XQ'),
  ('nathan.johnson@lightspeedsystems.com', 'A0YW'),
  ('scott.meeks@lightspeedsystems.com', 'A0QX'),
  ('shad.mcgaha@lightspeedsystems.com', 'A1C1'),
  ('whitney.veatch@lightspeedsystems.com', 'A0YY'),
  ('sinead.williams@lightspeedsystems.com', 'A0V2'),
  ('zakkiyya.purnell@lightspeedsystems.com', 'A11H'),
  ('kurstye.tillmon@lightspeedsystems.com', 'A11M'),
  ('nykayla.carter@lightspeedsystems.com', 'A0ZS'),
  ('angela.mazza@lightspeedsystems.com', 'A0ZC'),
  ('alexander.hesse@lightspeedsystems.com', 'A0XB'),
  ('ryan.stufflebeam@lightspeedsystems.com', 'A0Q3'),
  ('wing.mar@lightspeedsystems.com', 'A0RL'),
  ('esteban.diocares@lightspeedsystems.com', 'A0UR'),
  ('ryan.oglesby@lightspeedsystems.com', 'A0U3'),
  ('anita.krueger@lightspeedsystems.com', 'A1CS'),
  ('eric.cruz@lightspeedsystems.com', 'A0UW'),
  ('jack.mcdonnell@lightspeedsystems.com', 'A0VD'),
  ('christian.trahan@lightspeedsystems.com', 'A0OA'),
  ('andrew.hecht@lightspeedsystems.com', 'A0R9'),
  ('christina.atkinson@lightspeedsystems.com', 'A0Z0'),
  ('quinten.oldaker@lightspeedsystems.com', 'A0YC'),
  ('ramy.sahouri@lightspeedsystems.com', 'A0RH'),
  ('joel.walmsley@lightspeedsystems.com', 'A1DH'),
  ('dante.munoz@lightspeedsystems.com', 'A1BV'),
  ('alex.wade@lightspeedsystems.com', 'A0X3'),
  ('jason.isaac@lightspeedsystems.com', 'A0OV'),
  ('mitchell.laurrenring@lightspeedsystems.com', 'A0QS'),
  ('keaton.smith@lightspeedsystems.com', 'A0XR'),
  ('sergio.villegas@lightspeedsystems.com', 'A0TO'),
  ('nicholas.zema@lightspeedsystems.com', 'A11Q'),
  ('christopher.spink@lightspeedsystems.com', 'A1CZ'),
  ('sam.howard.mr@lightspeedsystems.com', 'A1B8'),
  ('jaeden.richards@lightspeedsystems.com', 'A1BG'),
  ('erika.johnson@lightspeedsystems.com', 'A11U'),
  ('alecia.boggess@lightspeedsystems.com', 'A0V1'),
  ('ann.marie.martinez@lightspeedsystems.com', 'A11V'),
  ('michael.roddey@lightspeedsystems.com', 'A0Z7'),
  ('lauren.mcnair@lightspeedsystems.com', 'A1B3'),
  ('casey.butera@lightspeedsystems.com', 'A108'),
  ('ross.mcaden@lightspeedsystems.com', 'A0W7'),
  ('trevor.davis@lightspeedsystems.com', 'A0XM'),
  ('alexander.sands@lightspeedsystems.com', 'A1B7'),
  ('matthew.nelson@lightspeedsystems.com', 'A0YA'),
  ('austin.sweet@lightspeedsystems.com', 'A11Y'),
  ('colin.fulton@lightspeedsystems.com', 'A1D1'),
  ('robert.hancock@lightspeedsystems.com', 'A10R'),
  ('daniel.dunn@lightspeedsystems.com', 'A1AK'),
  ('alexander.crouse@lightspeedsystems.com', 'A1B1'),
  ('december.wilks@lightspeedsystems.com', 'A0VF'),
  ('tracy.craig@lightspeedsystems.com', 'A11A'),
  ('ricky.salter@lightspeedsystems.com', 'A1FH'),
  ('jolie.boodansingh@lightspeedsystems.com', 'A118'),
  ('colleen.clark@lightspeedsystems.com', 'A0Y5'),
  ('lydell.craig@lightspeedsystems.com', 'A119'),
  ('cristal.cuellar@lightspeedsystems.com', 'A10J'),
  ('nathan.davila@lightspeedsystems.com', 'A10L'),
  ('jerry.flores@lightspeedsystems.com', 'A11C'),
  ('shanna.johnson@lightspeedsystems.com', 'A0ZT'),
  ('christina.mares@lightspeedsystems.com', 'A0ZR'),
  ('jason.montes@lightspeedsystems.com', 'A11F'),
  ('katelin.revels@lightspeedsystems.com', 'A11I'),
  ('shakira.romero@lightspeedsystems.com', 'A11K'),
  ('danielle.rubio@lightspeedsystems.com', 'A0ZU'),
  ('armahn.turk@lightspeedsystems.com', 'A11O'),
  ('marlisa.mungo@lightspeedsystems.com', 'A1AZ'),
  ('tameka.smith@lightspeedsystems.com', 'A1AY'),
  ('danielle.adams@lightspeedsystems.com', 'A1BD'),
  ('rashida.brown@lightspeedsystems.com', 'A1BF'),
  ('albert.garcia@lightspeedsystems.com', 'A1BE'),
  ('kian.curran@lightspeedsystems.com', 'A1BC'),
  ('nathan.estrada@lightspeedsystems.com', 'A1BH'),
  ('william.hellemsmoody@lightspeedsystems.com', 'A1B5'),
  ('andy.bennetta@lightspeedsystems.com', 'A1CR'),
  ('luke.shearin@lightspeedsystems.com', 'A0ZM'),
  ('cameron.meyer@lightspeedsystems.com', 'A10D'),
  ('enrique.michel@lightspeedsystems.com', 'A0OQ'),
  ('chasity.lyson@lightspeedsystems.com', 'A0P2'),
  ('michelle.mcgovern@lightspeedsystems.com', 'A0TE'),
  ('vernie.ogden@lightspeedsystems.com', 'A0RM'),
  ('leigh.morris@lightspeedsystems.com', 'A1DS'),
  ('travis.bullock@lightspeedsystems.com', 'A10T'),
  ('juan.rodriguez.maldonado@lightspeedsystems.com', 'A0OR'),
  ('frank.romero@lightspeedsystems.com', 'A124'),
  ('marie.wittry@lightspeedsystems.com', 'A0PX'),
  ('lewis.brown@lightspeedsystems.com', 'A1DT'),
  ('jide.oke@lightspeedsystems.com', 'A1DG'),
  ('khaled.uddin@lightspeedsystems.com', 'A1DO'),
  ('krista.delk@lightspeedsystems.com', 'A0YN'),
  ('cindy.moore@lightspeedsystems.com', 'A11G'),
  ('samantha.revels@lightspeedsystems.com', 'A11J'),
  ('gregory.funk@lightspeedsystems.com', 'A0NT'),
  ('ryan.bond@lightspeedsystems.com', 'A0QD'),
  ('jai.pandu@lightspeedsystems.com', 'A111'),
  ('jared.accardo@lightspeedsystems.com', 'A0Q7'),
  ('kevin.askew@lightspeedsystems.com', 'A113'),
  ('michael.boggess@lightspeedsystems.com', 'A0Q5'),
  ('michael.durando@lightspeedsystems.com', 'A0PM'),
  ('matthew.burg@lightspeedsystems.com', 'A0U9'),
  ('jennifer.duer@lightspeedsystems.com', 'A0ZZ')
) AS m(email, code)
WHERE u.email = m.email AND u.external_id IS DISTINCT FROM m.code;
--> statement-breakpoint

-- 2) Vacant seats as open-req directory nodes (name prefixed '(Vacant)').
INSERT INTO users (sub, email, name, title, is_active) VALUES
  ('seed:vacant.1@lightspeedsystems.com', 'vacant.1@lightspeedsystems.com', '(Vacant) Account Manager', 'Account Manager', true),
  ('seed:vacant.2@lightspeedsystems.com', 'vacant.2@lightspeedsystems.com', '(Vacant) Account Manager', 'Account Manager', true),
  ('seed:vacant.3@lightspeedsystems.com', 'vacant.3@lightspeedsystems.com', '(Vacant) Associate Systems Administrator', 'Associate Systems Administrator', true),
  ('seed:vacant.4@lightspeedsystems.com', 'vacant.4@lightspeedsystems.com', '(Vacant) Director, Campaigns', 'Director, Campaigns', true),
  ('seed:vacant.5@lightspeedsystems.com', 'vacant.5@lightspeedsystems.com', '(Vacant) EVP Product', 'EVP Product', true),
  ('seed:vacant.6@lightspeedsystems.com', 'vacant.6@lightspeedsystems.com', '(Vacant) Intern', 'Intern', true),
  ('seed:vacant.7@lightspeedsystems.com', 'vacant.7@lightspeedsystems.com', '(Vacant) Junior AI Automation Engineer', 'Junior AI Automation Engineer', true),
  ('seed:vacant.8@lightspeedsystems.com', 'vacant.8@lightspeedsystems.com', '(Vacant) Lead Software Engineer', 'Lead Software Engineer', true),
  ('seed:vacant.9@lightspeedsystems.com', 'vacant.9@lightspeedsystems.com', '(Vacant) QA Engineer', 'QA Engineer', true),
  ('seed:vacant.10@lightspeedsystems.com', 'vacant.10@lightspeedsystems.com', '(Vacant) Strategic Account Executive', 'Strategic Account Executive', true),
  ('seed:vacant.11@lightspeedsystems.com', 'vacant.11@lightspeedsystems.com', '(Vacant) Team Lead Technical Support', 'Team Lead Technical Support', true)
ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, is_active = true, updated_at = now();
--> statement-breakpoint

-- 3) Vacant seats: manager (primary supervisor) + department.
UPDATE users u SET manager_id = p.id, updated_at = now()
FROM (VALUES
  ('vacant.1@lightspeedsystems.com', 'michael.durando@lightspeedsystems.com'),
  ('vacant.2@lightspeedsystems.com', 'shaun.phillips@lightspeedsystems.com'),
  ('vacant.3@lightspeedsystems.com', 'patrick.chapa@lightspeedsystems.com'),
  ('vacant.4@lightspeedsystems.com', 'amy.bennett@lightspeedsystems.com'),
  ('vacant.5@lightspeedsystems.com', 'brian.thomas@lightspeedsystems.com'),
  ('vacant.6@lightspeedsystems.com', 'bradley.white@lightspeedsystems.com'),
  ('vacant.7@lightspeedsystems.com', 'donal.mcmahon@lightspeedsystems.com'),
  ('vacant.8@lightspeedsystems.com', 'bryan.anderson@lightspeedsystems.com'),
  ('vacant.9@lightspeedsystems.com', 'rebecca.gould@lightspeedsystems.com'),
  ('vacant.10@lightspeedsystems.com', 'michael.boggess@lightspeedsystems.com'),
  ('vacant.11@lightspeedsystems.com', 'travis.bullock@lightspeedsystems.com')
) AS m(email, mgr_email)
JOIN users p ON p.email = m.mgr_email
WHERE u.email = m.email;
--> statement-breakpoint

UPDATE users u SET department_id = d.id, updated_at = now()
FROM (VALUES
  ('vacant.1@lightspeedsystems.com', 'Customer Success'),
  ('vacant.2@lightspeedsystems.com', 'Sales'),
  ('vacant.3@lightspeedsystems.com', 'MIS'),
  ('vacant.4@lightspeedsystems.com', 'Marketing'),
  ('vacant.5@lightspeedsystems.com', 'Product Management'),
  ('vacant.6@lightspeedsystems.com', 'Human Resource'),
  ('vacant.7@lightspeedsystems.com', 'Administration'),
  ('vacant.8@lightspeedsystems.com', 'Product Development'),
  ('vacant.9@lightspeedsystems.com', 'QAT'),
  ('vacant.10@lightspeedsystems.com', 'Sales'),
  ('vacant.11@lightspeedsystems.com', 'Customer Service')
) AS m(email, dept)
JOIN departments d ON d.name = m.dept
WHERE u.email = m.email;
