-- 0061 Reconcile teams (departments) to the official org chart and remove the
-- leftover generic template seeds. Source: 'Lightspeed Systems — Org Chart'
-- re-provided by Brooke 2026-07-21. Two parts:
--   (A) Re-assert every person's department_id from the org chart (idempotent
--       set-based UPDATE by canonical email), so the app's team membership
--       matches the chart exactly even if it drifted via UI edits.
--   (B) Delete the 6 generic template departments and 13 generic template job
--       titles that are NOT on the org chart (kept: Marketing, Sales, Customer
--       Success, Senior Software Engineer, Account Executive — they also appear
--       on the chart). users.department_id / users.job_title_id are ON DELETE
--       SET NULL, so any stray non-chart reference is cleared rather than
--       blocking. Part A runs first so no charted person is on a generic dept
--       at delete time.

-- (A) Re-assert department membership from the org chart.
UPDATE users u SET department_id = d.id, updated_at = now()
FROM (VALUES
  ('spencer.smith@lightspeedsystems.com', 'Sales'),
  ('andrew.fowler@lightspeedsystems.com', 'Sales'),
  ('kiah.long@lightspeedsystems.com', 'Sales'),
  ('harry.saunders@lightspeedsystems.com', 'Sales'),
  ('shaun.phillips@lightspeedsystems.com', 'Sales'),
  ('christopher.dunn@lightspeedsystems.com', 'Sales'),
  ('jake.de.la.garrigue@lightspeedsystems.com', 'Sales'),
  ('nicole.greig@lightspeedsystems.com', 'Sales'),
  ('alexander.woods@lightspeedsystems.com', 'Product Management'),
  ('tu.ngo@lightspeedsystems.com', 'Customer Service'),
  ('syed.muhammad.hassaan.gillani@lightspeedsystems.com', 'Customer Service'),
  ('alexander.szabo@lightspeedsystems.com', 'Product Management'),
  ('jared.varner@lightspeedsystems.com', 'Product Management'),
  ('kyle.olson@lightspeedsystems.com', 'Marketing'),
  ('brian.thomas@lightspeedsystems.com', 'Administration'),
  ('donal.mcmahon@lightspeedsystems.com', 'Administration'),
  ('amy.bennett@lightspeedsystems.com', 'Marketing'),
  ('christopher.travis@lightspeedsystems.com', 'Sales'),
  ('robert.mcmillan@lightspeedsystems.com', 'Product Development'),
  ('john.genter@lightspeedsystems.com', 'Product Development'),
  ('chase.masiel@lightspeedsystems.com', 'Content Categorization'),
  ('hailey.thomas@lightspeedsystems.com', 'Content Categorization'),
  ('alyssa.ann.silva@lightspeedsystems.com', 'Customer Service'),
  ('jeffrey.smith@lightspeedsystems.com', 'QAT'),
  ('saul.trejo@lightspeedsystems.com', 'Customer Service'),
  ('katy.shawcross@lightspeedsystems.com', 'Customer Service'),
  ('brian.truong@lightspeedsystems.com', 'Data Science'),
  ('amanda.gorena@lightspeedsystems.com', 'Marketing'),
  ('heather.james@lightspeedsystems.com', 'Human Resource'),
  ('tania.mackie.mrs@lightspeedsystems.com', 'Sales'),
  ('caitlin.mcdermott@lightspeedsystems.com', 'Product Management'),
  ('zachary.horn@lightspeedsystems.com', 'Administration'),
  ('kenneth.chitwood@lightspeedsystems.com', 'Product Development'),
  ('derek.laurie@lightspeedsystems.com', 'Product Management'),
  ('madelyne.stewart@lightspeedsystems.com', 'Marketing'),
  ('kevin.chiang@lightspeedsystems.com', 'Administration'),
  ('kevin.lawrence@lightspeedsystems.com', 'Administration'),
  ('james.laprocido@lightspeedsystems.com', 'Finance'),
  ('jake.bowman@lightspeedsystems.com', 'Finance'),
  ('katherine.williamson@lightspeedsystems.com', 'Administration'),
  ('wengel.huluka@lightspeedsystems.com', 'Product Development'),
  ('colin.mccabe@lightspeedsystems.com', 'Sales'),
  ('morgan.canales@lightspeedsystems.com', 'Human Resource'),
  ('paul.chapa@lightspeedsystems.com', 'Human Resource'),
  ('hadley.james@lightspeedsystems.com', 'Human Resource'),
  ('thayer.kacher@lightspeedsystems.com', 'Human Resource'),
  ('ava.friloux@lightspeedsystems.com', 'Human Resource'),
  ('olivia.gibbons@lightspeedsystems.com', 'Human Resource'),
  ('emma.stewart@lightspeedsystems.com', 'Human Resource'),
  ('bryan.steele@lightspeedsystems.com', 'Human Resource'),
  ('lillian.fox@lightspeedsystems.com', 'Human Resource'),
  ('winter.rhoden@lightspeedsystems.com', 'Human Resource'),
  ('dhillon.reddy@lightspeedsystems.com', 'Human Resource'),
  ('braedon.mulder@lightspeedsystems.com', 'Human Resource'),
  ('benjamin.thomas@lightspeedsystems.com', 'Human Resource'),
  ('jade.friedman@lightspeedsystems.com', 'Human Resource'),
  ('brooke.friedman@lightspeedsystems.com', 'Human Resource'),
  ('jonathan.adkins@lightspeedsystems.com', 'Administration'),
  ('megan.black@lightspeedsystems.com', 'Marketing'),
  ('liam.roberts@lightspeedsystems.com', 'Marketing'),
  ('ryan.passanisi@lightspeedsystems.com', 'Administration'),
  ('sabrina.drouin@lightspeedsystems.com', 'Administration'),
  ('kyle.escobar@lightspeedsystems.com', 'QAT'),
  ('joseph.decarlo@lightspeedsystems.com', 'Security and Hosting'),
  ('matthew.ames@lightspeedsystems.com', 'Product Development'),
  ('trung.pham@lightspeedsystems.com', 'QAT'),
  ('michelle.vargas@lightspeedsystems.com', 'QAT'),
  ('van.mualcin@lightspeedsystems.com', 'Product Development'),
  ('aiyana.mathew@lightspeedsystems.com', 'Product Development'),
  ('christopher.newkirk@lightspeedsystems.com', 'Security and Hosting'),
  ('robert.bruce@lightspeedsystems.com', 'Product Development'),
  ('preston.matheson@lightspeedsystems.com', 'Product Development'),
  ('perry.sittser@lightspeedsystems.com', 'Product Development'),
  ('carl.ahlstrand@lightspeedsystems.com', 'Product Development'),
  ('justin.woolverton@lightspeedsystems.com', 'Product Development'),
  ('jason.veselka@lightspeedsystems.com', 'Student Safety'),
  ('tichiere.womble@lightspeedsystems.com', 'Student Safety'),
  ('abraham.ybarra@lightspeedsystems.com', 'Customer Service'),
  ('dylan.claiborne@lightspeedsystems.com', 'Customer Service'),
  ('alexander.doria@lightspeedsystems.com', 'Data Science'),
  ('michael.waszazak@lightspeedsystems.com', 'Product Management'),
  ('juliana.morris@lightspeedsystems.com', 'Administration'),
  ('scott.dunham@lightspeedsystems.com', 'Finance'),
  ('bradley.rowe@lightspeedsystems.com', 'Sales Engineers'),
  ('richard.chown@lightspeedsystems.com', 'Sales Engineers'),
  ('charles.bryant@lightspeedsystems.com', 'Sales Engineers'),
  ('william.long@lightspeedsystems.com', 'Sales Engineers'),
  ('grace.mellette@lightspeedsystems.com', 'Marketing'),
  ('marcos.suarez@lightspeedsystems.com', 'Marketing'),
  ('douglas.dietert@lightspeedsystems.com', 'Finance'),
  ('kirk.orgeldinger@lightspeedsystems.com', 'Administration'),
  ('bradley.white@lightspeedsystems.com', 'Security and Compliance'),
  ('rebecca.gould@lightspeedsystems.com', 'Product Management'),
  ('jiana.khazma@lightspeedsystems.com', 'Product Marketing'),
  ('charushila.awhad@lightspeedsystems.com', 'QAT'),
  ('madhuri.balasubramanya@lightspeedsystems.com', 'QAT'),
  ('nicholas.chambers@lightspeedsystems.com', 'QAT'),
  ('brandon.jones@lightspeedsystems.com', 'QAT'),
  ('brooke.brown@lightspeedsystems.com', 'Sales'),
  ('nicole.tribo@lightspeedsystems.com', 'Sales'),
  ('adrian.rios.alvarez@lightspeedsystems.com', 'MIS'),
  ('megan.duhon@lightspeedsystems.com', 'Finance'),
  ('adrienne.synos@lightspeedsystems.com', 'Finance'),
  ('steven.miller.junior@lightspeedsystems.com', 'Administration'),
  ('alyssa.russo@lightspeedsystems.com', 'Sales Operations'),
  ('niels.dhollanderbarclay@lightspeedsystems.com', 'Data Science'),
  ('teresa.reuter@lightspeedsystems.com', 'Administration'),
  ('gerard.jr.dantel@lightspeedsystems.com', 'Product Development'),
  ('patrick.chapa@lightspeedsystems.com', 'MIS'),
  ('gregory.artzt@lightspeedsystems.com', 'Product Management'),
  ('rachel.thompson@lightspeedsystems.com', 'Sales Operations'),
  ('robert.mccartney@lightspeedsystems.com', 'Customer Service'),
  ('brock.anderson@lightspeedsystems.com', 'Administration'),
  ('bryan.anderson@lightspeedsystems.com', 'Product Development'),
  ('brock.meadors@lightspeedsystems.com', 'Product Development'),
  ('kevin.lasher@lightspeedsystems.com', 'Product Development'),
  ('casey.hann@lightspeedsystems.com', 'Sales'),
  ('wesley.cunningham@lightspeedsystems.com', 'Sales Engineers'),
  ('larissa.negreiros.somaio@lightspeedsystems.com', 'Product Marketing'),
  ('gijo.johny@lightspeedsystems.com', 'QAT'),
  ('jenisha.karmacharya@lightspeedsystems.com', 'QAT'),
  ('andrew.cribari@lightspeedsystems.com', 'QAT'),
  ('jeffrey.zwick@lightspeedsystems.com', 'QAT'),
  ('steven.landwehr@lightspeedsystems.com', 'Product Development'),
  ('neil.shaw@lightspeedsystems.com', 'Product Development'),
  ('nathan.johnson@lightspeedsystems.com', 'Product Development'),
  ('scott.meeks@lightspeedsystems.com', 'Sales'),
  ('shad.mcgaha@lightspeedsystems.com', 'Sales Engineers'),
  ('whitney.veatch@lightspeedsystems.com', 'Student Safety'),
  ('sinead.williams@lightspeedsystems.com', 'Student Safety'),
  ('zakkiyya.purnell@lightspeedsystems.com', 'Student Safety'),
  ('kurstye.tillmon@lightspeedsystems.com', 'Student Safety'),
  ('nykayla.carter@lightspeedsystems.com', 'Student Safety'),
  ('angela.mazza@lightspeedsystems.com', 'Student Safety'),
  ('alexander.hesse@lightspeedsystems.com', 'MIS'),
  ('ryan.stufflebeam@lightspeedsystems.com', 'Customer Success Engineering'),
  ('wing.mar@lightspeedsystems.com', 'Customer Service'),
  ('esteban.diocares@lightspeedsystems.com', 'Security and Hosting'),
  ('ryan.oglesby@lightspeedsystems.com', 'Security and Hosting'),
  ('anita.krueger@lightspeedsystems.com', 'Security and Hosting'),
  ('eric.cruz@lightspeedsystems.com', 'Product Development'),
  ('jack.mcdonnell@lightspeedsystems.com', 'Product Development'),
  ('christian.trahan@lightspeedsystems.com', 'Product Development'),
  ('andrew.hecht@lightspeedsystems.com', 'Product Development'),
  ('christina.atkinson@lightspeedsystems.com', 'Customer Success Engineering'),
  ('quinten.oldaker@lightspeedsystems.com', 'Customer Success Engineering'),
  ('ramy.sahouri@lightspeedsystems.com', 'Customer Success Engineering'),
  ('joel.walmsley@lightspeedsystems.com', 'Customer Success Engineering'),
  ('dante.munoz@lightspeedsystems.com', 'Customer Success Engineering'),
  ('alex.wade@lightspeedsystems.com', 'Product Development'),
  ('jason.isaac@lightspeedsystems.com', 'Product Development'),
  ('mitchell.laurrenring@lightspeedsystems.com', 'Product Development'),
  ('keaton.smith@lightspeedsystems.com', 'Sales'),
  ('sergio.villegas@lightspeedsystems.com', 'Sales'),
  ('nicholas.zema@lightspeedsystems.com', 'Sales'),
  ('christopher.spink@lightspeedsystems.com', 'Sales'),
  ('sam.howard.mr@lightspeedsystems.com', 'Sales'),
  ('jaeden.richards@lightspeedsystems.com', 'Sales'),
  ('erika.johnson@lightspeedsystems.com', 'Sales'),
  ('alecia.boggess@lightspeedsystems.com', 'Sales'),
  ('ann.marie.martinez@lightspeedsystems.com', 'Sales'),
  ('michael.roddey@lightspeedsystems.com', 'Sales'),
  ('lauren.mcnair@lightspeedsystems.com', 'Sales'),
  ('casey.butera@lightspeedsystems.com', 'Sales'),
  ('ross.mcaden@lightspeedsystems.com', 'Sales'),
  ('trevor.davis@lightspeedsystems.com', 'Sales Engineers'),
  ('alexander.sands@lightspeedsystems.com', 'Sales Engineers'),
  ('matthew.nelson@lightspeedsystems.com', 'Sales Engineers'),
  ('austin.sweet@lightspeedsystems.com', 'Sales Engineers'),
  ('colin.fulton@lightspeedsystems.com', 'Sales Engineers'),
  ('robert.hancock@lightspeedsystems.com', 'Sales Engineers'),
  ('daniel.dunn@lightspeedsystems.com', 'Sales Engineers'),
  ('alexander.crouse@lightspeedsystems.com', 'Sales Engineers'),
  ('december.wilks@lightspeedsystems.com', 'Student Safety'),
  ('tracy.craig@lightspeedsystems.com', 'Student Safety'),
  ('ricky.salter@lightspeedsystems.com', 'Student Safety'),
  ('jolie.boodansingh@lightspeedsystems.com', 'Student Safety'),
  ('colleen.clark@lightspeedsystems.com', 'Student Safety'),
  ('lydell.craig@lightspeedsystems.com', 'Student Safety'),
  ('cristal.cuellar@lightspeedsystems.com', 'Student Safety'),
  ('nathan.davila@lightspeedsystems.com', 'Student Safety'),
  ('jerry.flores@lightspeedsystems.com', 'Student Safety'),
  ('shanna.johnson@lightspeedsystems.com', 'Student Safety'),
  ('christina.mares@lightspeedsystems.com', 'Student Safety'),
  ('jason.montes@lightspeedsystems.com', 'Student Safety'),
  ('katelin.revels@lightspeedsystems.com', 'Student Safety'),
  ('shakira.romero@lightspeedsystems.com', 'Student Safety'),
  ('danielle.rubio@lightspeedsystems.com', 'Student Safety'),
  ('armahn.turk@lightspeedsystems.com', 'Student Safety'),
  ('marlisa.mungo@lightspeedsystems.com', 'Student Safety'),
  ('tameka.smith@lightspeedsystems.com', 'Student Safety'),
  ('danielle.adams@lightspeedsystems.com', 'Student Safety'),
  ('rashida.brown@lightspeedsystems.com', 'Student Safety'),
  ('albert.garcia@lightspeedsystems.com', 'Student Safety'),
  ('kian.curran@lightspeedsystems.com', 'Student Safety'),
  ('nathan.estrada@lightspeedsystems.com', 'Student Safety'),
  ('william.hellemsmoody@lightspeedsystems.com', 'MIS'),
  ('andy.bennetta@lightspeedsystems.com', 'Customer Service'),
  ('luke.shearin@lightspeedsystems.com', 'Sales Operations'),
  ('cameron.meyer@lightspeedsystems.com', 'Customer Service'),
  ('enrique.michel@lightspeedsystems.com', 'Customer Service'),
  ('chasity.lyson@lightspeedsystems.com', 'Customer Service'),
  ('michelle.mcgovern@lightspeedsystems.com', 'Scrum'),
  ('vernie.ogden@lightspeedsystems.com', 'Scrum'),
  ('leigh.morris@lightspeedsystems.com', 'QAT'),
  ('travis.bullock@lightspeedsystems.com', 'Customer Service'),
  ('juan.rodriguez.maldonado@lightspeedsystems.com', 'Customer Service'),
  ('frank.romero@lightspeedsystems.com', 'Customer Service'),
  ('marie.wittry@lightspeedsystems.com', 'Customer Service'),
  ('lewis.brown@lightspeedsystems.com', 'Customer Service'),
  ('jide.oke@lightspeedsystems.com', 'Customer Service'),
  ('khaled.uddin@lightspeedsystems.com', 'Customer Service'),
  ('krista.delk@lightspeedsystems.com', 'Customer Success'),
  ('cindy.moore@lightspeedsystems.com', 'Customer Success'),
  ('samantha.revels@lightspeedsystems.com', 'Customer Success'),
  ('gregory.funk@lightspeedsystems.com', 'Finance'),
  ('ryan.bond@lightspeedsystems.com', 'Product Development'),
  ('jai.pandu@lightspeedsystems.com', 'Product Development'),
  ('jared.accardo@lightspeedsystems.com', 'QAT'),
  ('kevin.askew@lightspeedsystems.com', 'Sales'),
  ('michael.boggess@lightspeedsystems.com', 'Sales'),
  ('michael.durando@lightspeedsystems.com', 'Sales'),
  ('matthew.burg@lightspeedsystems.com', 'Product Management'),
  ('jennifer.duer@lightspeedsystems.com', 'Product Management')
) AS m(email, dept)
JOIN departments d ON d.name = m.dept
WHERE u.email = m.email;
--> statement-breakpoint

-- (B1) Remove leftover generic departments not on the org chart.
DELETE FROM departments WHERE name IN (
  'Engineering',
  'Product',
  'Design',
  'People / HR',
  'Finance / G&A',
  'Analytics'
);
--> statement-breakpoint

-- (B2) Remove leftover generic job titles not on the org chart.
DELETE FROM job_titles WHERE title IN (
  'Software Engineer I',
  'Software Engineer II',
  'Staff Engineer',
  'Engineering Manager',
  'Product Manager',
  'Senior Product Manager',
  'Product Designer',
  'Designer',
  'Data Scientist',
  'Senior Analyst',
  'Analyst',
  'Support Specialist',
  'Support Lead'
);
