-- AIE 2026-07-27 — ensure every department/title from the HR export exists in
-- the managed lookups so employee FKs resolve. Idempotent (ON CONFLICT DO NOTHING).
INSERT INTO "departments" ("name","sort_order") VALUES
  ('Administration', 900),
  ('Content Categorization', 901),
  ('Customer Service', 902),
  ('Customer Success', 903),
  ('Customer Success Engineering', 904),
  ('Data Science', 905),
  ('Finance', 906),
  ('Human Resource', 907),
  ('MIS', 908),
  ('Marketing', 909),
  ('Product Development', 910),
  ('Product Management', 911),
  ('Product Marketing', 912),
  ('QAT', 913),
  ('Sales', 914),
  ('Sales Engineers', 915),
  ('Sales Operations', 916),
  ('Scrum', 917),
  ('Security and Compliance', 918),
  ('Security and Hosting', 919),
  ('Student Safety', 920)
ON CONFLICT ("name") DO NOTHING;
--> statement-breakpoint
INSERT INTO "job_titles" ("title","sort_order") VALUES
  ('Account Executive', 900),
  ('Account Manager', 901),
  ('Acting Director of Sales EMEIA', 902),
  ('Associate Account Executive', 903),
  ('Associate Account Manager', 904),
  ('Associate Technical Product Manager', 905),
  ('Associate Technical Support Specialist', 906),
  ('Business Analyst', 907),
  ('Business Development Representative', 908),
  ('CEO & Founder', 909),
  ('CISO', 910),
  ('Chief AI Officer', 911),
  ('Chief Revenue Officer', 912),
  ('Chief Technology Officer', 913),
  ('Chief of Staff', 914),
  ('Content Categorization Specialist', 915),
  ('Customer Operations Analyst', 916),
  ('Customer Quality Manager', 917),
  ('Customer Service Representative', 918),
  ('Data Platform Manager', 919),
  ('Director Corporate Marketing', 920),
  ('Director Human Resources', 921),
  ('Director International Safeguarding & Digital Transformation', 922),
  ('Director Site Reliability', 923),
  ('Director Technical Product Management', 924),
  ('Director of Product Management Analytics', 925),
  ('Director of Strategic Programs', 926),
  ('EVP Finance and Corporate Development', 927),
  ('EVP Product', 928),
  ('EVP, Operations', 929),
  ('Events Manager', 930),
  ('Financial Analyst', 931),
  ('Front Office Coordinator/Executive Assistant', 932),
  ('Front-End Engineer', 933),
  ('General Manager International', 934),
  ('Human Resources Business Partner', 935),
  ('Human Resources Contractor', 936),
  ('Intern', 937),
  ('Internal Learning & Development Manager', 938),
  ('International Marketing Coordinator', 939),
  ('International Marketing Manager', 940),
  ('Junior AI Automation Engineer', 941),
  ('Junior Contracts Administrator', 942),
  ('Junior QA Engineer', 943),
  ('Junior Site Reliability Engineer', 944),
  ('Junior Software Engineer', 945),
  ('Lead QA Automation Engineer', 946),
  ('Lead QA Engineer', 947),
  ('Lead Senior Software Engineer', 948),
  ('Lead Site Reliability Engineer', 949),
  ('Lead Software Engineer', 950),
  ('Lead Student Safety Specialist', 951),
  ('Lead Technical Support Specialist', 952),
  ('Machine Learning Engineer', 953),
  ('Manager Finance', 954),
  ('Manager Product Design', 955),
  ('Manager, Contracts', 956),
  ('Manager, Strategic Solutions Engineering', 957),
  ('Marketing Coordinator', 958),
  ('Marketing Manager', 959),
  ('Orders and Accounts Receivables Specialist', 960),
  ('President & CFO', 961),
  ('Principal Application Security Engineer', 962),
  ('Principal Technical Product Manager', 963),
  ('Product Marketing Manager', 964),
  ('QA Automation Engineer', 965),
  ('QA Engineer', 966),
  ('Renewals Specialist', 967),
  ('Salesforce Product Manager', 968),
  ('Senior AI Automation Engineer', 969),
  ('Senior Accountant', 970),
  ('Senior Accounting Manager', 971),
  ('Senior Customer Operations Manager', 972),
  ('Senior Data Engineer', 973),
  ('Senior Director Customer Operations', 974),
  ('Senior Director Engineering', 975),
  ('Senior Director MIS', 976),
  ('Senior Director Product Management', 977),
  ('Senior Director Solutions Engineering & Support', 978),
  ('Senior Director Strategic Programs', 979),
  ('Senior Engineering Manager', 980),
  ('Senior Front-End Engineer', 981),
  ('Senior Manager Customer Experience', 982),
  ('Senior Manager, Solutions Engineering', 983),
  ('Senior Product Marketing Manager', 984),
  ('Senior QA Automation Engineer', 985),
  ('Senior QA Engineer', 986),
  ('Senior Software Engineer', 987),
  ('Senior Staff Software Engineer', 988),
  ('Senior Strategic Account Executive', 989),
  ('Senior Strategic Solutions Engineer', 990),
  ('Senior Student Safety Specialist', 991),
  ('Senior Systems Administrator', 992),
  ('Senior Technical Escalation Engineer', 993),
  ('Senior Technical Support Specialist', 994),
  ('Site Reliability Engineer', 995),
  ('Software Engineer', 996),
  ('Solutions Architect', 997),
  ('Solutions Engineer', 998),
  ('Staff Frontend Engineer', 999),
  ('Staff Software Engineer', 1000),
  ('Strategic Account Executive', 1001),
  ('Strategic Account Manager', 1002),
  ('Strategic Solutions Engineer', 1003),
  ('Student Safety Manager', 1004),
  ('Student Safety Specialist', 1005),
  ('Systems Administrator', 1006),
  ('Team Lead Technical Support', 1007),
  ('Team Lead, Revenue Operations', 1008),
  ('Technical Escalation Engineer', 1009),
  ('Technical Product Manager', 1010),
  ('Technical Support Manager', 1011),
  ('Technical Support Specialist', 1012),
  ('Training & Enablement Manager', 1013),
  ('VP Corporate Controller', 1014),
  ('VP Engineering', 1015),
  ('VP Product Delivery', 1016),
  ('VP Sales', 1017),
  ('VP, Product IT Solutions', 1018)
ON CONFLICT ("title") DO NOTHING;
